### ISSUE TITLE
[BUG]  Download to pdf generates an empty PDF file

### ISSUE THREAD

**Issue by varunpan** [AmruthPillai/Reactive-Resume#1005]
**Describe the bug**
Download to pdf generates an empty PDF file - Same issue as https://github.com/AmruthPillai/Reactive-Resume/issues/1004#issue-1370678531

I looked over the issue there and I cannot seem to understand what to do to fix it. One comment mentions something about env variable but the only thing related to PDF export is PUBLIC_SERVER_URL where it said default is `http://localhost/api`. On the repo, in the env.example it is empty. On the Repo, the docker-compose shows this value as `http://localhost:3100`. I have it set to `http://192.168.1.4:3100` however should this be set to my PUBLIC_SERVER_URL: `resumeserver.domain.tld` or `http://192.168.1.4:3100/api`?

Another comment mentions something about rabbit URL, but there is no instructions for how to configure? is it an ENV variable? Looking at the RabbitURL docs, it says something about from and to URL, what should they be set to for this issue?

Also when I change the `PUBLIC_URL` and `PUBLIC_SERVER_URL` to use `localhost` instead of `192.168.1.4`, then I am unable to login and get an error message that said `n is undefined`. I manually checked the PostgresDB and it still has my user and resume information. is there something I'm missing?

**Product Flavor**

- [x] Self Hosted

**To Reproduce**

1. After logging in, inputting all of my resume information
2. Click on 'export to PDF'
3. Download the file
4. Click to open it, and blank PDF

**Expected behavior**

I expected to see a pdf generated as what was seen on the app

**Screenshots**

**Desktop (please complete the following information):**

- OS: Debian - Docker
- Browser Firefox
- Version 104

**Additional context**

My docker-compose.yml (please note that I have a separate docker container with postgres server running):

```
version: "3.8"

services:
  server:
    image: amruthpillai/reactive-resume:server-latest
    container_name: RRserver
    restart: always
    ports:
      - 3100:3100
    depends_on:
      - postgres
    environment:
      - TZ=America/New_York
      - PUBLIC_URL=${PUBLIC_URL}
      - PUBLIC_SERVER_URL=${PUBLIC_SERVER_URL}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY_TIME=604800
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
  client:
    image: amruthpillai/reactive-resume:client-latest
    container_name: RRclient
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - RRserver
    environment:
      - TZ=America/New_York
      - PUBLIC_FLAG_DISABLE_SIGNUPS=true
      - PUBLIC_URL=${PUBLIC_URL}
      - PUBLIC_SERVER_URL=${PUBLIC_SERVER_URL}
```

See my below my env file:

```
POSTGRES_DB=reactiveresume
POSTGRES_USER=reactiveresume
POSTGRES_PASSWORD=<redacted>
SECRET_KEY=<redacted>
POSTGRES_HOST=192.168.1.4
POSTGRES_PORT=5432
JWT_SECRET=<redacted>
GOOGLE_API_KEY=<redacted>
PUBLIC_URL=http://192.168.1.4:3000
PUBLIC_SERVER_URL=http://192.168.1.4:3100
```
