### ISSUE TITLE
[BUG] Not able to register

### ISSUE THREAD

**Issue by The-Inamati** [AmruthPillai/Reactive-Resume#1009]
**Describe the bug**

I am unable to register. I have tried everything that is said on all similar bugs but nothing works. When pressing register I get a 404 error from the server. 

There is nothing in the server logs.

My Compose is 
```
 resumedb:
    image: postgres:14.2-alpine
    container_name: resumedb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - database
    volumes:
      - resumedb:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      start_period: 15s
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always

resumeback:
    image: amruthpillai/reactive-resume:server-latest
    container_name: resumeback
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
      - database
    environment:
      - TZ=$TZ
      - PUBLIC_URL=https://resume.domain.com
      - PUBLIC_SERVER_URL=https://resume.domain.com/api
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SECRET_KEY=RANDOM_SECRET
      - POSTGRES_HOST=resumedb
      - POSTGRES_PORT=5432
      - JWT_SECRET=RANDOM_SECRET
      - JWT_EXPIRY_TIME=604800
    depends_on:
      - resumedb
    volumes:
      - resumeback:/app/server/dist/assets/uploads
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.resumeback.entrypoints=https"
      - "traefik.http.routers.resumeback.rule=Host(`resume.domain.com`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.resumeback.tls=true"
      ## HTTP Services
      - "traefik.http.routers.resumeback.service=resumeback"
      - "traefik.http.middlewares.resume-api.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.resume-api.stripprefix.forceslash=true"
      - "traefik.http.services.resumeback.loadbalancer.server.port=3100"
      - "traefik.http.routers.resumeback.middlewares=chain-no-auth@file"

 resumefront:
    image: amruthpillai/reactive-resume:client-latest
    container_name: resumefront
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
      - database
    environment:
      - TZ=$TZ
      - PUBLIC_URL=https://resume.domain.com
      - PUBLIC_SERVER_URL=https://resume.domain.com/api
      - PUBLIC_FLAG_DISABLE_SIGNUPS=false
    depends_on:
      - resumeback
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.resumefront.entrypoints=https"
      - "traefik.http.routers.resumefront.rule=Host(`resume.domain.com`)"
      - "traefik.http.routers.resumefront.tls=true"
      ## HTTP Services
      - "traefik.http.routers.resumefront.service=resumefront"
      - "traefik.http.services.resumefront.loadbalancer.server.port=3000"
      - "traefik.http.routers.resumefront.middlewares=chain-no-auth@file"
```
Traefik gets a 404 error when forwarding the GET request

![image](https://user-images.githubusercontent.com/45592340/192111088-76fdf47b-82ea-4932-a3d1-98e58a4b0205.png)

When I curl the url https://resume.domain.com/api/auth/register I get the following:

{"statusCode":404,"message":"Cannot GET /api/auth/register","timestamp":"2022-09-24T17:18:10.930Z","path":"/api/auth/register"}

**Product Flavor**

- [x] Self Hosted

I apologize if I'm doing anything wrong but I can't seem to find out what is happening.
