### ISSUE TITLE
[BUG] No access to dashboard behind reverse proxy

### ISSUE THREAD

**Issue by tehniemer** [AmruthPillai/Reactive-Resume#1072]
**Describe the bug**

I've been fighting this one for a while and made some headway, but now I've hit a wall again. It seems that there is some issue communicating from the client to the server when behind a reverse proxy. I'm able to login to the app, but when I try to access it I get a blank screen. If I set it up for local access only by using the IP address and port numbers of the host I'm able to get to the dashboard and the application seems to run fine (other than [PDF export](https://github.com/AmruthPillai/Reactive-Resume/issues/721)). This [comment](https://github.com/AmruthPillai/Reactive-Resume/issues/801#issuecomment-1279381595) seems to be similar to what I'm experiencing. 

**Product Flavor**

- [ ] Managed (https://rxresu.me)
- [x] Self Hosted

**To Reproduce**

Set up like this:
```
## Reactive Resume - A Free and Open-Source Resume Builder That Respects Your Privacy
  rxresume-server:
    image: amruthpillai/reactive-resume:server-latest
    container_name: rxresume-server
    restart: unless-stopped
    networks:
      - proxy
      - internal
    ports:
      - '3100:3100'
    depends_on:
      - postgres12
    security_opt:
      - no-new-privileges:true
    logging:
      options:
        max-size: '2m'
        max-file: '3'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/opt/docker/rxresume/exports:/app/server/dist/assets/exports'
      - '/opt/docker/rxresume/uploads:/app/server/dist/assets/uploads'
    environment:
      TZ: $TIMEZONE
      PUBLIC_URL:  https://resume.$DOMAINNAME
      PUBLIC_SERVER_URL: https://resume.$DOMAINNAME
      POSTGRES_DB: rxresume
      POSTGRES_USER: $POSTGRES_DB_USER
      POSTGRES_PASSWORD: $POSTGRES_DB_PASS
      POSTGRES_HOST: postgres12
      POSTGRES_PORT: 5432
      SECRET_KEY: $RXRESUME_SECRET_KEY
      JWT_SECRET: $RXRESUME_JWT_SECRET
      JWT_EXPIRY_TIME: 604800
      GOOGLE_API_KEY: $RR_GOOGLE_API_KEY
      MAIL_FROM_NAME: 'Reactive Resume'
      MAIL_FROM_EMAIL: $EMAIL_USER
      MAIL_HOST: $EMAIL_HOST
      MAIL_PORT: $EMAIL_PORT
      MAIL_USERNAME: $EMAIL_USER
      MAIL_PASSWORD: $RXRESUME_MAIL_PASS
      STORAGE_S3_ENABLED: 'false'
    labels:
      - 'autoheal=true'
      - 'traefik.enable=true'
      ## HTTP Routers
      - 'traefik.http.routers.resumeserver-rtr.entrypoints=https'
      - 'traefik.http.routers.resumeserver-rtr.rule=Host(`resume.$DOMAINNAME`) && PathPrefix(`/api/`)'
      ## Middlewares
      - 'traefik.http.routers.resumeserver-rtr.middlewares=chain-no-auth@file,resume-api' # No Authentication
      - 'traefik.http.middlewares.resume-api.stripprefix.prefixes=/api'
      - 'traefik.http.middlewares.resume-api.stripprefix.forceslash=true'
      ## HTTP Services
      - 'traefik.http.routers.resumeserver-rtr.service=resumeserver-svc'
      - 'traefik.http.services.resumeserver-svc.loadbalancer.server.port=3100'

  rxresume-client:
    image: amruthpillai/reactive-resume:client-latest
    container_name: rxresume-client
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - '3000:3000'
    depends_on:
      - rxresume-server
    security_opt:
      - no-new-privileges:true
    logging:
      options:
        max-size: '2m'
        max-file: '3'
    environment:
      TZ: $TIMEZONE
      PUBLIC_URL:  https://resume.$DOMAINNAME
      PUBLIC_SERVER_URL: https://resume.$DOMAINNAME
      GOOGLE_API_KEY: $RR_GOOGLE_API_KEY
      PUBLIC_FLAG_DISABLE_SIGNUPS: 'true'
    labels:
      - 'autoheal=true'
      - 'traefik.enable=true'
      ## HTTP Routers
      - 'traefik.http.routers.resume-rtr.entrypoints=https'
      - 'traefik.http.routers.resume-rtr.rule=Host(`resume.$DOMAINNAME`)'
      ## Middlewares
      - 'traefik.http.routers.resume-rtr.middlewares=chain-no-auth@file' # No Authentication      
      ## HTTP Services
      - 'traefik.http.routers.resume-rtr.service=resume-svc'
      - 'traefik.http.services.resume-svc.loadbalancer.server.port=3000'
```

**Expected behavior**

Dashboard loads and application works behind a reverse proxy

**Desktop (please complete the following information):**

- OS: `Debian 11`
- Browser: `Edge`
- Version: `amruthpillai/reactive-resume:*-latest`

**Additional context**

Traefik log.
```
[11/Nov/2022:12:37:21 +0000] "GET /resume HTTP/2.0" 404 846 "-" "-" 1 "resume-rtr@docker" "http://192.168.100.13:3000" 5ms
[11/Nov/2022:12:37:34 +0000] "GET /resume/auth/login?secretKey= HTTP/2.0" 404 846 "-" "-" 11 "resume-rtr@docker" "http://192.168.100.13:3000" 8ms
[11/Nov/2022:12:37:35 +0000] "GET /resume HTTP/2.0" 404 846 "-" "-" 16 "resume-rtr@docker" "http://192.168.100.13:3000" 4ms
[11/Nov/2022:12:37:36 +0000] "GET /resume HTTP/2.0" 404 846 "-" "-" 17 "resume-rtr@docker" "http://192.168.100.13:3000" 12ms
[11/Nov/2022:12:37:38 +0000] "GET /resume HTTP/2.0" 404 846 "-" "-" 18 "resume-rtr@docker" "http://192.168.100.13:3000" 4ms
```
