### ISSUE TITLE
[BUG] Can't recolor level bars

### ISSUE THREAD

**Issue by EndBug** [AmruthPillai/Reactive-Resume#1146]
**Describe the bug**

As of now, the `--primary-color` variable is transformed into rgb when creating the level bars for skills, languages, etc, so you can't edit their color in the custom CSS tab using `--primary-color`.

As a workaround, you can use a selector to match each color chip like this: 
```css
.mr-1.h-3.w-4.rounded.border-2 {
    border-color: var(--primary-color) !important;
}
```

The problem is that if you do the same with the `background-color` property then there will be no empty chips, since there's no way to distinguish full and empty chips.

**Product Flavor**

- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

1. Open a resume in the resume editor
2. Add a section with a level number (like a language)
3. Go to the Custom CSS Editor and try to change the color of the skill bar associated to that level number.

**Expected behavior**

I'd suggest assigning a class to full, half-full, and empty chips, plus using `--primary-color` without converting it to rgb.

**Screenshots**

Without any custom CSS: 
<img width="187" alt="image" src="https://user-images.githubusercontent.com/26386270/208949920-3f45b16c-4a4c-443e-9b80-be5855e79327.png">

Using the following custom CSS:
```css
* {
    --primary-color: #2a5162
}

.mr-1.h-3.w-4.rounded.border-2 {
    border-color: var(--primary-color) !important;
}
```
<img width="173" alt="image" src="https://user-images.githubusercontent.com/26386270/208950127-202b9db9-6d1a-4252-8030-c9354f9873b7.png">

Using the following custom CSS:
```css
* {
    --primary-color: #2a5162
}

.mr-1.h-3.w-4.rounded.border-2 {
    border-color: var(--primary-color) !important;
    background-color: var(--primary-color) !important;;
}
```
<img width="164" alt="image" src="https://user-images.githubusercontent.com/26386270/208950402-3c790ef2-b728-40c3-a79f-873c5d6befb8.png">

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Brave
- Version: 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)
