### ISSUE TITLE
[BUG] Profile Photo/PDF Export Issues

### ISSUE THREAD

**Issue by blaine07** [AmruthPillai/Reactive-Resume#1174]
**Describe the bug**

**Product Flavor**

- [ ] Managed (https://rxresu.me)
- [ ✅] Self Hosted

**To Reproduce**

I have Reactive Resume running as two containers in Unraid(well Server and client; DB in existing container on server)

In the server container I have a defined “exports” mnt and “uploads” mnt. Profile photos show in storage when I upload one. 

Anytime I try to upload a Profile photo, it just shows photo icon(lightning bolt thing) on resume; anytime I try to export as PDF nothing ever happens. 

What could I/do I need to check to get photos and videos export working? I am sure it’s my own fault, somehow, just not sure what issue is?

**Expected behavior**

To be able to upload working Profile Photos and export Resume as a PDF. 

I’m sure what’s wrong is my fault; I just need a little help figuring out exactly what I’ve got wrong.  :-(

**Comment by ykorzikowski** [comment]
Hey, 

I just had the same error, but I solved it. It was a misconfiguration with `PUBLIC_URL` and `PUBLIC_SERVER_URL`. 

I am using Nginx as reverse proxy. Here is my working configuration: 

```
server {
    listen *:80;
    listen [::]:80;
    server_name cv.***.com;

    location / {
        return 301 https://cv.***.com$request_uri;
    }
}
server {
    include security.conf;
    listen *:443 ssl;
    listen [::]:443 ssl;
    ssl_certificate /etc/letsencrypt/live/***.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/***.com/privkey.pem;
    server_name cv-api.***.com;

    access_log      /var/log/nginx/***.com/cv-api.log;
    error_log       /var/log/nginx/***.com/err/cv-api.log;

    location / {
       proxy_pass http://10.10.10.116:19001/;

       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
       proxy_set_header Host $http_host;

       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto https;
       proxy_set_header X-Nginx-Proxy true;

       proxy_redirect off;
    }

}

server {
    include security.conf;
    listen *:443 ssl;
    listen [::]:443 ssl;
    ssl_certificate /etc/letsencrypt/live/***.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/***.com/privkey.pem;
    server_name cv.***.com;

    access_log      /var/log/nginx/***.com/cv.log;
    error_log       /var/log/nginx/***.com/err/cv.log;

    location / {
       proxy_pass http://10.10.10.116:19000/;

       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
       proxy_set_header Host $http_host;

       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto https;
       proxy_set_header X-Nginx-Proxy true;

       proxy_redirect off;
    }
}
```

docker-compose.yml
```
version: "3.8"

services:

  server:
    image: amruthpillai/reactive-resume:server-latest
    restart: always
    ports:
      - 19001:3100
    environment:
      PUBLIC_URL: https://cv.***.com
      PUBLIC_SERVER_URL: https://cv-api.***.com
      POSTGRES_DB: reactivecvdb
      POSTGRES_USER: reactivecv
      POSTGRES_PASSWORD: ""
      SECRET_KEY: ""
      POSTGRES_HOST: 10.10.10.103
      POSTGRES_PORT: 5432
      JWT_SECRET: ""
      JWT_EXPIRY_TIME: 604800
      MAIL_FROM_NAME: Reactive Resume
      MAIL_FROM_EMAIL: noreply@***.eu
      MAIL_HOST: mail.***.eu
      MAIL_PORT: 25
      MAIL_USERNAME: noreply@***.eu
      MAIL_PASSWORD: ""

  client:
    image: amruthpillai/reactive-resume:client-latest
    restart: always
    ports:
      - 19000:3000
    depends_on:
      - server
    environment:
      - PUBLIC_URL=https://cv.***.com
      - PUBLIC_SERVER_URL=https://cv-api.***.com
```
