### ISSUE TITLE
OS/arch linux/arm64 missing

### ISSUE THREAD

**Issue by stef4ik** [AmruthPillai/Reactive-Resume#1249]
Hello, just found out that the docker image is not build anymore for linux/arm64. Does this have a reason? Could you keep providing the linux/arm64-image?

Thanks a lot

**Comment by AlexTu2** [comment]
I made an issue here as well, #1328 
In the mean time you could change your docker-compose.yml to build the images yourself.

```
version: "3.8"

services:
  postgres:
    image: postgres:alpine
    platform: linux/arm64
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 15s
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  server:
    platform: linux/arm64
    build:
      context: .
      dockerfile: ./server/Dockerfile
    restart: always
    ports:
      - 3100:3100
    depends_on:
      - postgres
    environment:
      - PUBLIC_URL=
      - PUBLIC_SERVER_URL=
      - PUBLIC_GOOGLE_CLIENT_ID=
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SECRET_KEY=change-me-to-something-secure
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_SSL_CERT=
      - JWT_SECRET=change-me-to-something-secure
      - JWT_EXPIRY_TIME=604800
      - GOOGLE_CLIENT_SECRET=
      - GOOGLE_API_KEY=
      - MAIL_FROM_NAME=Reactive Resume
      - MAIL_FROM_EMAIL=noreply@rxresu.me
      - MAIL_HOST=
      - MAIL_PORT=
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - STORAGE_BUCKET=
      - STORAGE_REGION=
      - STORAGE_ENDPOINT=
      - STORAGE_URL_PREFIX=
      - STORAGE_ACCESS_KEY=
      - STORAGE_SECRET_KEY=
      - STORAGE_S3_ENABLED=false
      - PDF_DELETION_TIME=

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      - PUBLIC_URL=
      - PUBLIC_SERVER_URL=
      - PUBLIC_GOOGLE_CLIENT_ID=

volumes:
  pgdata:

```
