### ISSUE TITLE
[BUG] Unable to register/login due to mixed content (https and http)

### ISSUE THREAD

**Issue by opsder** [AmruthPillai/Reactive-Resume#1317]
**Describe the bug**

Unable to register/login due to mixed content (https and http)

**Product Flavor**

- [ ] Managed (https://rxresu.me)
- [x] Self Hosted

**To Reproduce**

1. Install using the docker-compose file example
2. Configure cloudflare tunnel to the good ports 
3. Access https://resume.xxxxxx.com 
4. Try to register/login

**Expected behavior**

Be able to register/login

**Screenshots**

On register button click : 
Blocage du chargement du contenu mixte actif (mixed active content) « **http**://resume.xxxxxx.com/api/auth/register »

It seems like it is trying to load the api trough http but it's forbideen as the main website is on https://resume.xxxxxx.com/

**Desktop (please complete the following information):**

- OS: ubuntu server 22.04
- Browser chrome, safari
- Version lastest docker image

**Additional context**

I have first tried without traefik without sucess, then I added it and ther is my docker-compose file : 

```
version: "3.8"

services:
  postgres:
    image: postgres:alpine
    container_name: rxresume-db
    restart: always
    expose:
      - 5432
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/rxresume/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 15s
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres2
    networks:
      - proxy

  server:
    image: amruthpillai/reactive-resume:server-latest
    container_name: rxresume-server
    restart: always
    #extra_hosts:
    #  - "resume.xxxxxx.com:10.10.0.100" # optionally enable if PDF export keeps failing; specify your domain and server's IP address where traefik is running
    expose:
      - 3100
    depends_on:
      - postgres
    environment:
      - PUBLIC_URL=https://resume.xxxxxx.com
      - PUBLIC_SERVER_URL=https://resume.xxxxxx.com/api # only change the subdomain, leave /api as is
      - PUBLIC_GOOGLE_CLIENT_ID=
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SECRET_KEY=change-me-to-something-ecure
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_SSL_CERT=
      - JWT_SECRET=change-me-to-something-ecure
      - JWT_EXPIRY_TIME=604800
      - GOOGLE_CLIENT_SECRET=
      - GOOGLE_API_KEY=
      - MAIL_FROM_NAME=Reactive Resume
      - MAIL_FROM_EMAIL=noreply@rxresu.me
      - MAIL_HOST=
      - MAIL_PORT=
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - STORAGE_BUCKET=
      - STORAGE_REGION=
      - STORAGE_ENDPOINT=
      - STORAGE_URL_PREFIX=
      - STORAGE_ACCESS_KEY=
      - STORAGE_SECRET_KEY=
      - PDF_DELETION_TIME=
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.rxresume-server.rule=Host(`resume.xxxxxx.com`) && PathPrefix(`/api`) # only change the subdomain, leave /api as is
      - traefik.http.services.rxresume-server.loadbalancer.server.port=3100
      - traefik.docker.network=proxy
      # Part for optional traefik middlewares
      - traefik.http.routers.rxresume-server.middlewares=path-strip # may add local-ipwhitelist@file for access control
      - traefik.http.middlewares.path-strip.stripprefix.prefixes=/api 
      - traefik.http.middlewares.path-strip.stripprefix.forceSlash=false

  client:
    image: amruthpillai/reactive-resume:client-latest
    container_name: rxresume-client
    restart: always
    #extra_hosts:
    #  - "resume.xxxxxx.com:10.10.0.100" # # optionally enable if PDF export keeps failing; specify your domain and server's IP address where traefik is running
    expose:
      - 3000
    depends_on:
      - server
    environment:
      - PUBLIC_URL=https://resume.xxxxxx.com
      - PUBLIC_SERVER_URL=https://resume.xxxxxx.com/api # only change the subdomain, leave /api as is
      - PUBLIC_GOOGLE_CLIENT_ID=
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.rxresume-client.rule=Host(`resume.xxxxxx.com`)
      - traefik.http.services.rxresume-client.loadbalancer.server.port=3000
      - traefik.docker.network=proxy
      # Part for optional traefik middlewares
      #- traefik.http.routers.rxresume-client.middlewares=local-ipwhitelist@file # may enable this middleware for access control
      
  traefik:
    image: traefik:v2.10.1
    container_name: rxresume-traefik
    restart: unless-stopped
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 3035:80
      - 3036:8080
    environment:
      - VIRTUAL_HOST=resume.xxxxxx.com
      - VIRTUAL_PORT=80
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro      

networks:
  proxy:
    external: true

```

**Comment by PvtTwinkle** [comment]
I am also having the same issue except I am not even using traefik at all. I am just having cloudflare tunnel point my DNS record to http://<ip-address>:3100. I can log in just fine when accessing http://<ip-address>:3100. When accessing "https://resume.xxxxxxxxxx.com" through the cloudflare tunnel, I am brought to the site but after entering the credentials and clicking "login" nothing happens. I have tried using "http://<ip-address>:3100" and "http://resume.xxxxxxx.com" and "https://resume.xxxxxxxxx.com" for the PUBLIC_URL variable. 

`My docker-compose.yml file:
postgres:
    image: postgres:alpine
    container_name: rr-postgresdb
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - /path/to/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 15s
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      PUID: 1001
      PGID: 3001
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: <secret-password>
  server:
    image: amruthpillai/reactive-resume:server-latest
    container_name: rr-server
    restart: unless-stopped
    ports:
      - 3100:3100
    depends_on:
      - postgres
    environment:
      PUID: 1001
      PGID: 3001
      PUBLIC_URL: http://resume.xxxxxxxxxxxxxx.com
      PUBLIC_SERVER_URL: http://<ipaddress>:3100
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: <secret-password>
      SECRET_KEY: <secret-key>
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      JWT_SECRET: <secret-jwt>
      JWT_EXPIRY_TIME: 604800
  client:
    image: amruthpillai/reactive-resume:client-latest
    container_name: rr-client
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      PUID: 1001
      PGID: 3001
      PUBLIC_URL: http://resume.xxxxxxxxxxxxxxxxx.com
      PUBLIC_SERVER_URL: http://<ipaddress>:3100`

**Comment by opsder** [comment]
As I am not the only one, it seems like it call a http url even if we specify a https url in every variable. Any idea of where/why ?

**Comment by Klomgor** [comment]
I have the same exact issue. I tried with only Bind9 acting as my DNS server. I tried with only Traefik working as a reverse proxy. I tried with both Bind9 and Traefik working together. All leading to the same conclusion.

All the options that involves using FQDN the login button doesn't work, albeit working perfectly fine when using the local ip address.

**Comment by jlar0che** [comment]
Same problem here. Can't get past the registration after a fresh install...

**Comment by jlar0che** [comment]
Sorted out the issue. I forgot to create a DNS entry for both the Reactive Resume SERVER and the Reactive Resume (access) sites.

**Comment by opsder** [comment]
@jlar0che May you please explain which services you use and which error(s) you got ? 
It seems like it was a different issue.

**Comment by PvtTwinkle** [comment]
I was finally able to get it to work, albeit with a different reverse proxy, NPM. I believe the issue is that the reverse proxy needs to be configured with two locations. One location (subdomain.domain.com) to point to the client for the https page. The other (/api/) to point to the server for the /api (needed for login). [This person](https://github.com/AmruthPillai/Reactive-Resume/issues/721#issuecomment-1405283786) explains it pretty well and I was able to follow his instructions to get it working.

**Comment by AlexTu2** [comment]
> I was finally able to get it to work, albeit with a different reverse proxy, NPM. I believe the issue is that the reverse proxy needs to be configured with two locations. One location (subdomain.domain.com) to point to the client for the https page. The other (/api/) to point to the server for the /api (needed for login). [This person](https://github.com/AmruthPillai/Reactive-Resume/issues/721#issuecomment-1405283786) explains it pretty well and I was able to follow his instructions to get it working.

@PvtTwinkle Are you able to export to PDF and upload a picture to your resume?

I'm having issues with those features, also using NPM

**Comment by PvtTwinkle** [comment]
> > I was finally able to get it to work, albeit with a different reverse proxy, NPM. I believe the issue is that the reverse proxy needs to be configured with two locations. One location (subdomain.domain.com) to point to the client for the https page. The other (/api/) to point to the server for the /api (needed for login). [This person](https://github.com/AmruthPillai/Reactive-Resume/issues/721#issuecomment-1405283786) explains it pretty well and I was able to follow his instructions to get it working.
> 
> @PvtTwinkle Are you able to export to PDF and upload a picture to your resume?
> 
> I'm having issues with those features, also using NPM

I am able to export to PDF and upload a picture to my resume. I haven't used it too much, but it seems to be working fine for me. Have you verified it isn't an issue with your browser/client? Here is my docker-compose configuration and NPM configuration. Obviously, everything in <> is set to my environment. Hopefully, this helps. 
```
postgres:
    image: postgres:alpine
    container_name: rr-postgresdb
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - </path/to/data>:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 15s
      interval: 30s
      timeout: 30s
      retries: 3
    user: <xxxx>:<xxxx>
    environment:
      POSTGRES_DB: <POSTGRES_DB_NAME>
      POSTGRES_USER: <POSTGRES_USER>
      POSTGRES_PASSWORD: <POSTGRES_PW>
  server:
    image: amruthpillai/reactive-resume:server-latest
    container_name: rr-server
    restart: unless-stopped
    ports:
      - 3100:3100
    depends_on:
      - postgres
    environment:
      PUID: <xxxx>
      PGID: <xxxx>
      PUBLIC_URL: https://<subdomain.example.com>/
      PUBLIC_SERVER_URL: https://subdomain.example.com/api
      POSTGRES_DB: <POSTGRES_DB_NAME>
      POSTGRES_USER: <POSTGRES_USER>
      POSTGRES_PASSWORD: <POSTGRES_PW>
      SECRET_KEY: <SECRET_KEY>
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      JWT_SECRET: <JWT_SECRET>
      JWT_EXPIRY_TIME: 604800
  client:
    image: amruthpillai/reactive-resume:client-latest
    container_name: rr-client
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      PUID: <xxxx>
      PGID: <xxxx>
      PUBLIC_URL: https://<subdomain.example.com>/
      PUBLIC_SERVER_URL: https://<subdomain.example.com
```
![Screenshot 2023-06-04 204438](https://github.com/AmruthPillai/Reactive-Resume/assets/88509142/4cf1d77d-25cc-4f20-9836-04dbc37f2446)
![Screenshot 2023-06-04 204526](https://github.com/AmruthPillai/Reactive-Resume/assets/88509142/e6b1e1ae-52a4-4440-92d0-ed82b357be6c)
