### ISSUE TITLE
[Bug] Unable to register / create account

### ISSUE THREAD

**Issue by Ejz9** [AmruthPillai/Reactive-Resume#1438]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues

### Product Variant

Self-Hosted

### Current Behavior

I run the default docker-compose listed in Reactive-Resume Git Hub. I am deploying the docker-compose through portainer. Portainer creates a stack with the Postgres-db, reactResume server, and reactResume client. In the logs, the db shows nothing of error. The server shows nothing of error. The client shows nothing of error.

Yet when I attempt to "register" I am greeted with the inability to. The status bar when you click "register" crosses the just below my search bar a couple of times before disappearing. The screen does not change otherwise. There is no hint of what might be wrong. I've re-deployed the stack many times attempting various ideas or potential solutions I thought might work. I have also deployed the stack with adminer so I could see if the db was actually getting written to. When you register an account, it is not getting written to. Yet some point during the setup/startup of everything the server must have some connection to the db cause it creates "users" and "resumes" tables. There are no entries in these tables. I have even tried entering the data to make an account manually. No resolve.

I've seen this issue has persisted for a long time and previous reports were open about the same thing. I also believe the docker guide is a bit lackluster. The docs that exist do guide you somewhat but when you already have a docker-compose. A tool that many individuals already use, why is there not a section for it in the docs, or at least how to set it up? Docker makes deploying something like this incredibly easy, simple, and convenient. But the existing docker-compose just does not work, or there's some error that many other individuals like myself are similarly having. It's discouraging to deal with.

The most common cause? I'm presuming some database-to-server error. They communicate initially it seems but fail to maintain a connection afterward or there is some hiccup. Noting is printed in logs (at least docker logs for each container). You can visibly see when it is not able to connect though as if you changed ex: the db-host env variable to something other than "postgres" the server spits out the issue in its logs.

### Expected Behavior

I would expect that I could create an account on my self-hosted version of this program. Which other issues might be presented but presumably would be minor and easily fixed. I would also expect the logs to state when an error has occurred with anything.

### Steps To Reproduce

1. Grab or copy this docker-compose file: https://github.com/AmruthPillai/Reactive-Resume/blob/main/compose.yml
2. Deploy with whatever tool you manage your docker-compose files with. I used portainer and added it as an app template. From this, I adjusted the external ports for myself and deployed the stack to which no issues were shown by portainer.
3. Visit the site: default is http://your-ip/your-domain:3000 to visit the client landing page. Mine was port 5000 for outside of the container. It still brings you to the same place.
4. Go to the top left of the page where it says register and fill out the information.
5. Click register after filling out the required information. Watch for a status bar at the top (just below the search bar) and expect that it does not proceed with creating the account or displaying anything more.

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Anything else?

I'm doing this on OperaGX but it did not work on the other three browsers when I tested. I do not believe it is a browser issue.

**Comment by darsh12** [comment]
I am having the same issues:

```yaml
# .env
PUBLIC_URL=192.168.68.201:3000
PUBLIC_SERVER_URL=192.168.68.201:3100
PUBLIC_FLAG_DISABLE_SIGNUPS=false
```

```yaml
server:
    image: amruthpillai/reactive-resume:server-latest
    restart: always
    ports:
      - 3100:3100
    depends_on:
      - postgres
    environment:
      - PUBLIC_URL=${PUBLIC_URL}
      - PUBLIC_SERVER_URL=${PUBLIC_SERVER_URL}
        [...]
        [..]

client:
    image: amruthpillai/reactive-resume:client-latest
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      - PUBLIC_URL=${PUBLIC_URL}
      - PUBLIC_SERVER_URL=${PUBLIC_SERVER_URL}
      - PUBLIC_FLAG_DISABLE_SIGNUPS=${PUBLIC_FLAG_DISABLE_SIGNUPS}
```
```bash
# Trying to register a user
user at 14:01:15 in ~ [I] ➜ curl http://192.168.68.201:3100/auth/register -H "Content-Type: application/json" -d '{"name":"john","email":"john.doe@example.com","username":"john","password":"password"}' -L -v
*   Trying 192.168.68.201:3100...
* Connected to 192.168.68.201 (192.168.68.201) port 3100 (#0)
> POST /auth/register HTTP/1.1
> Host: 192.168.68.201:3100
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 99
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< X-Powered-By: Express
< Vary: Origin
< Access-Control-Allow-Credentials: true
< Content-Type: application/json; charset=utf-8
< Content-Length: 81
< ETag: W/"51-RIZt+OId6cProF0r1sQE2IJcx3I"
< Date: Sat, 26 Aug 2023 21:01:33 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
* Connection #0 to host 192.168.68.201 left intact
{"statusCode":401,"timestamp":"2023-08-26T21:01:33.250Z","path":"/auth/register"}% 
```

I seem to getting a 401 error.

I also tried to login with an existing user, grabbing the JWT and passing it as `Authorization: Bearer <TOKEN>` and I still get the 401 error.

At this point I have exhausted all options.
