### ISSUE TITLE
[Bug] Website works for split of a second

### ISSUE THREAD

**Issue by KamilKleina** [AmruthPillai/Reactive-Resume#1528]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues

### Product Variant

Self-Hosted

### Current Behavior

Hello,
website does work only for a split second after that it goes grey. Same stuff directly on container and also by traefik. Tried like 2-3 browsers on my PC and my phone.
[screen-recording.webm](https://github.com/AmruthPillai/Reactive-Resume/assets/104216718/b302791d-ed45-41da-9c4c-84e6c7ffb549)

Here is my docker-compose
```
version: '3.8'
services:
  reactive-resume:
    image: amruthpillai/reactive-resume:latest
    container_name: reactive-resume
    restart: unless-stopped
    ports:
      - 8097:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reactive-resume.entrypoints=webs"
      - "traefik.http.routers.reactive-resume.rule=Host(`reactive-resume.ubuntu.home.kleikk.com`)"
      - "traefik.http.routers.reactive-resume.tls=true"
      - "traefik.http.services.reactive-resume.loadbalancer.server.port=80"
      - "traefik.http.services.reactive-resume.loadbalancer.server.scheme=http"
```

### Expected Behavior

Website working properly.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Anything else?

Logs from my container:
[_reactive-resume_logs(1).txt](https://github.com/AmruthPillai/Reactive-Resume/files/13298804/_reactive-resume_logs.1.txt)
