### ISSUE TITLE
[Bug] Access Denied When Exporting To PDF (Self-Hosted Docker)

### ISSUE THREAD

**Issue by My-Random-Thoughts** [AmruthPillai/Reactive-Resume#1621]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Self-Hosted

### Current Behavior

Getting the below error message when clicking the Export To PDF button:

I am not using any proxy or other middleware software

```
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied.</Message>
  <Key>resumes/clpiiwkmu0003h69ugw0fj139.pdf</Key>
  <BucketName>clpiivuar0000h69ucr044fhi</BucketName>
  <Resource>
    /clpiivuar0000h69ucr044fhi/resumes/clpiiwkmu0003h69ugw0fj139.pdf
  </Resource>
  <RequestId>179BD4E8929888A2</RequestId>
  <HostId>
    7987905dee74cdeb212432486a178e511309594cee7cb75f892cd53e35f09ea4
  </HostId>
</Error>
```

### Expected Behavior

A PDF file is generated and downloaded

### What browsers are you seeing the problem on?

Firefox

### What template are you using?

Nosepass

### Anything else?

Docker File:

In this line, `PUBLIC_URL: http://home.lan:3000` resolves to the IP of my docker host

```
version: "3.8"
services:
  # Database (Postgres)
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Storage (for image uploads)
  minio:
    image: minio/minio
    restart: unless-stopped
    command: server /data --address :9001
    ports:
      - 9001:9001
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  # Chrome Browser (for printing and previews)
  chrome:
    image: browserless/chrome:1.61.0-puppeteer-21.4.1
    restart: unless-stopped
    environment:
      TOKEN: chrome_token
      EXIT_ON_HEALTH_FAILURE: true
      PRE_REQUEST_HEALTH_CHECK: true

  # Redis (for cache & server session management)
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --requirepass password

  app:
    image: amruthpillai/reactive-resume:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - minio
      - redis
      - chrome
    environment:
      # -- Environment Variables --
      PORT: 3000
      NODE_ENV: production

      # -- URLs --
      PUBLIC_URL: http://home.lan:3000
      STORAGE_URL: http://home.lan:9001

      # -- Printer (Chrome) --
      CHROME_TOKEN: chrome_token
      CHROME_URL: ws://chrome:3000

      # -- Database (Postgres) --
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres

      # -- Auth --
      ACCESS_TOKEN_SECRET: access_token_secret
      REFRESH_TOKEN_SECRET: refresh_token_secret

      # -- Storage (Minio) --
      STORAGE_ENDPOINT: minio
      STORAGE_PORT: 9001
      STORAGE_REGION: us-east-1 # Optional
      STORAGE_BUCKET: default
      STORAGE_ACCESS_KEY: minioadmin
      STORAGE_SECRET_KEY: minioadmin
      STORAGE_USE_SSL: false

      # -- Cache (Redis) --
      REDIS_URL: redis://default:password@redis:6379
      DISABLE_EMAIL_AUTH: false

volumes:
  minio_data:
  postgres_data:
```
