### ISSUE TITLE
[Feature] Better-documented examples of working docker-compose

### ISSUE THREAD

**Issue by Nachtschwingeswildhunt** [AmruthPillai/Reactive-Resume#1671]
### Is there an existing issue for this feature?

- [X] Yes, I have searched the existing issues and it doesn't exist.

### Feature Description

Hi everyone! I am having troubles setting up reactive resume on my server using docker compose. The [simple docker-compose on the github](https://github.com/AmruthPillai/Reactive-Resume/blob/main/tools/compose/simple.yml) does not work for me and I cannot find much about it in the documentation. Could you by any chance share some anonymized docker-compose without proxy that works?

**Comment by juliandaz11** [comment]
here -> [Docker composes](https://github.com/AmruthPillai/Reactive-Resume/tree/main/tools/compose)

**Comment by Nachtschwingeswildhunt** [comment]
Thank you for posting the exact folder I got the docker-compose from. Sadly even with these files (I even chose the simplest one) I could not manage to get reactive resume working, even though I managed to do so with quite a few other services. My original question still stands. Could someone share a real-life, anonymised  version?

**Comment by juliandaz11** [comment]
You must specify your error to assist you better. Perhaps I can help if you include the bucket name in the URL:
STORAGE_URL: http://localhost:9000/default

**Comment by lytn1ng** [comment]
Hi @Nachtschwingeswildhunt (and anyone else who's interested),
I managed to get it working (sort of) with this docker-compose.yml
```
version: "3.8"

# In this Docker Compose example, it assumes that you maintain a reverse proxy externally (or chose not to).
# The only two exposed ports here are from minio (:9000) and the app itself (:3000).
# If these ports are changed, ensure that the env vars passed to the app are also changed accordingly.

services:
  # Database (Postgres)
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Storage (for image uploads)
  minio:
    # image: minio/minio:latest
    image: minio/minio
    restart: unless-stopped
    # command: server --console-address ":9001" /data
    command: server /data
    ports:
      - 9080:9000
      - 9081:9001
    volumes:
      - minio_data:/data
    environment:
      MINIO_ADDRESS: :9000
      MINIO_CONSOLE_ADDRESS: :9001
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  # Chrome Browser (for printing and previews)
  chrome:
    image: browserless/chrome:1.61.0-puppeteer-21.4.1
    restart: unless-stopped
    environment:
      TOKEN: chrome_token
      EXIT_ON_HEALTH_FAILURE: "true"
      PRE_REQUEST_HEALTH_CHECK: "true"

  # Redis (for cache & server session management)
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --requirepass password
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  app:
    image: amruthpillai/reactive-resume:latest
    restart: unless-stopped
    ports:
      - 3030:3000
    depends_on:
      - chrome
      - minio
      - postgres
      - redis
    environment:
      # -- Environment Variables --
      PORT: 3000
      NODE_ENV: production

      # -- URLs --
      PUBLIC_URL: http://server.example.com:3030
      STORAGE_URL: http://server.example.com:9080

      # -- Printer (Chrome) --
      CHROME_TOKEN: chrome_token
      CHROME_URL: ws://chrome:3000

      # -- Database (Postgres) --
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/reactive_resumes

      # -- Auth --
      ACCESS_TOKEN_SECRET: access_token_secret
      REFRESH_TOKEN_SECRET: refresh_token_secret

      # -- Emails --
      MAIL_FROM: resumes@example.com
      SMTP_URL: smtp://email_user:email_password@email_server:587 # Optional

      # -- Storage (Minio) --
      STORAGE_ENDPOINT: minio
      STORAGE_PORT: 9000
      STORAGE_REGION: us-east-1 # Optional
      STORAGE_BUCKET: default
      STORAGE_ACCESS_KEY: minioadmin
      STORAGE_SECRET_KEY: minioadmin
      STORAGE_USE_SSL: "false"

      # -- Cache (Redis) --
      REDIS_URL: redis://default:password@redis:6379

      # -- Email --
      # DISABLE_EMAIL_AUTH: true

volumes:
  postgresql_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/reactive_resume/postgresql_data
      o: bind
  minio_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/reactive_resume/minio_data
      o: bind
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/reactive_resume/redis_data
      o: bind
```

I am running this docker-compose on a Linux server, and accessing http://server.example.com:3030 from a browser in another computer.

The one problem (so far) that I have encountered is that, if I generate a PDF of my resume, it opens a new browser tab (popup) with this error:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied.</Message>
<Key>resumes/clqa6ufd60001d0k9f1chddlv.pdf</Key>
<BucketName>clqa6tqej0000127pwqslk4k0</BucketName>
<Resource>/clqa6tqej0000127pwqslk4k0/resumes/clqa6ufd60001d0k9f1chddlv.pdf</Resource>
<RequestId>17A1C621D807D452</RequestId>
<HostId>dd9025bab4ad464b049177c95eb6ebf374d5b3fd10f9251148b698df7ac2eee8</HostId>
</Error>
```

I have tried every STORAGE_URL value in the docker-compose.yml that I can think of, but sadly it makes no difference.

But the good news is that the PDF is indeed generated and available on the server (under /opt/reactive_resume/minio_data...).
You can also log in to the Minio console (after enabling it on port 9001, and mapping that port  too) , and download the PDF.

Hopefully, this authentication problem can be resolved quickly to make the app - which looks very good otherwise - even better to use.

**Comment by lytn1ng** [comment]
I finally got it working, but only through a reverse proxy.

I also discovered that trailing slashes are required for the PUBLIC_URL and STORAGE_URL.

I configured reverse proxy entries (Nginx with SSL) as follows:
```
resume.example.com -> proxy_pass http://server.example.com:3030/
resume-storage.example.com -> proxy_pass http://server.example.com:9080/default/
```

Then, I changed these 2 lines in the docker-compose.yml that I posted above:
```
PUBLIC_URL: https://resume.example.com/
STORAGE_URL: https://resume-storage.example.com/
```

And everything seems to be working so far.

I still have no idea why it does not work if using these 2 values in the docker-compose (and without any reverse proxy):
PUBLIC_URL: http://server.example.com:3030/
STORAGE_URL: http://server.example.com:9080/default/

Without the reverse proxy, I keep seeing errors from the container like these, and the browser popup window opens a blank page:
```
app_1       | Trace: Error [TypeError]: Cannot read properties of null (reading 'cloneNode')
app_1       |     at evaluate (evaluate at processPage (/app/dist/apps/server/main.js:13195:45), <anonymous>:1:50)
app_1       |     at #evaluate (/app/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:229:55)
app_1       |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
app_1       |     at async ExecutionContext.evaluate (/app/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:126:16)
app_1       |     at async IsolatedWorld.evaluate (/app/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:128:16)
app_1       |     at async CdpFrame.evaluate (/app/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:363:20)
app_1       |     at async CdpPage.evaluate (/app/node_modules/.pnpm/puppeteer-core@21.5.2/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:744:20)
app_1       |     at async processPage (/app/dist/apps/server/main.js:13195:34)
app_1       |     at async PrinterService.generateResume (/app/dist/apps/server/main.js:13208:17)
app_1       |     at async /app/dist/apps/server/main.js:13133:25
app_1       |     at PrinterService.generateResume (/app/dist/apps/server/main.js:13239:21)
app_1       |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
app_1       |     at async /app/dist/apps/server/main.js:13133:25
app_1       |     at async UtilsService.getCachedOrSet (/app/dist/apps/server/main.js:11895:23)
app_1       |     at async ResumeService.printResume (/app/dist/apps/server/main.js:13978:21)
app_1       |     at async ResumeController.printResume (/app/dist/apps/server/main.js:13593:25)
```

**Comment by lytn1ng** [comment]
And of course, 5 minutes after posting this, I find the problem. It now works without a reverse proxy too.

The browser will complain about "insecure download" when you download the PDF, but you can still get the PDF version.

The problem, apparently, is:
PUBLIC_URL should NOT have any trailing slash.
STORAGE_URL MUST have a trailing slash.

And it took me far too many hours to find it. I agree with the main topic of this issue that this needs to be better documented. Hopefully, this example docker-compose.yml will help in achieving that:
```
version: "3.8"

services:
  # Database (Postgres)
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Storage (for image uploads)
  minio:
    # image: minio/minio:latest
    image: minio/minio
    restart: unless-stopped
    # command: server --console-address ":9001" /data
    command: server /data
    ports:
      - 9080:9000
      - 9081:9001
    volumes:
      - minio_data:/data
    environment:
      MINIO_ADDRESS: :9000
      MINIO_CONSOLE_ADDRESS: :9001
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  # Chrome Browser (for printing and previews)
  chrome:
    image: browserless/chrome:1.61.0-puppeteer-21.4.1
    restart: unless-stopped
    environment:
      TOKEN: chrome_token
      EXIT_ON_HEALTH_FAILURE: "true"
      PRE_REQUEST_HEALTH_CHECK: "true"

  # Redis (for cache & server session management)
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --requirepass password
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  app:
    image: amruthpillai/reactive-resume:latest
    restart: unless-stopped
    ports:
      - 3030:3000
    depends_on:
      - chrome
      - minio
      - postgres
      - redis
    environment:
      # -- Environment Variables --
      PORT: 3000
      NODE_ENV: production

      # -- URLs --
      PUBLIC_URL: http://server.example.com:3030
      STORAGE_URL: http://server.example.com:9080/default/

      # -- Printer (Chrome) --
      CHROME_TOKEN: chrome_token
      CHROME_URL: ws://chrome:3000

      # -- Database (Postgres) --
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/reactive_resumes

      # -- Auth --
      ACCESS_TOKEN_SECRET: access_token_secret
      REFRESH_TOKEN_SECRET: refresh_token_secret

      # -- Emails --
      MAIL_FROM: resumes@example.com
      SMTP_URL: smtp://email_user:email_password@email_server:587 # Optional

      # -- Storage (Minio) --
      STORAGE_ENDPOINT: minio
      STORAGE_PORT: 9000
      STORAGE_REGION: us-east-1 # Optional
      STORAGE_BUCKET: default
      STORAGE_ACCESS_KEY: minioadmin
      STORAGE_SECRET_KEY: minioadmin
      STORAGE_USE_SSL: "false"

      # -- Cache (Redis) --
      REDIS_URL: redis://default:password@redis:6379

      # -- Email --
      # DISABLE_EMAIL_AUTH: true

volumes:
  postgresql_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/reactive_resume/postgresql_data
      o: bind
  minio_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/reactive_resume/minio_data
      o: bind
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/reactive_resume/redis_data
      o: bind
```

**Comment by StreamlinedStartup** [comment]
Where's the Server image?

**Comment by lytn1ng** [comment]
@StreamlinedStartup: What server image are you talking about?

All the images used in the docker-compose are mentioned in the respective "image" definitions.

**Comment by Nachtschwingeswildhunt** [comment]
> And of course, 5 minutes after posting this, I find the problem. It now works without a reverse proxy too.
> 
> The browser will complain about "insecure download" when you download the PDF, but you can still get the PDF version.
> 
> The problem, apparently, is: PUBLIC_URL should NOT have any trailing slash. STORAGE_URL MUST have a trailing slash.
> 
> And it took me far too many hours to find it. I agree with the main topic of this issue that this needs to be better documented. Hopefully, this example docker-compose.yml will help in achieving that:
> 
> ```
> version: "3.8"
> 
> services:
>   # Database (Postgres)
>   postgres:
>     image: postgres:15-alpine
>     restart: unless-stopped
>     volumes:
>       - postgresql_data:/var/lib/postgresql/data
>     environment:
>       POSTGRES_DB: postgres
>       POSTGRES_USER: postgres
>       POSTGRES_PASSWORD: postgres
>     healthcheck:
>       test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
>       interval: 10s
>       timeout: 5s
>       retries: 5
> 
>   # Storage (for image uploads)
>   minio:
>     # image: minio/minio:latest
>     image: minio/minio
>     restart: unless-stopped
>     # command: server --console-address ":9001" /data
>     command: server /data
>     ports:
>       - 9080:9000
>       - 9081:9001
>     volumes:
>       - minio_data:/data
>     environment:
>       MINIO_ADDRESS: :9000
>       MINIO_CONSOLE_ADDRESS: :9001
>       MINIO_ROOT_USER: minioadmin
>       MINIO_ROOT_PASSWORD: minioadmin
> 
>   # Chrome Browser (for printing and previews)
>   chrome:
>     image: browserless/chrome:1.61.0-puppeteer-21.4.1
>     restart: unless-stopped
>     environment:
>       TOKEN: chrome_token
>       EXIT_ON_HEALTH_FAILURE: "true"
>       PRE_REQUEST_HEALTH_CHECK: "true"
> 
>   # Redis (for cache & server session management)
>   redis:
>     image: redis:alpine
>     restart: unless-stopped
>     command: redis-server --requirepass password
>     ports:
>       - 6379:6379
>     volumes:
>       - redis_data:/data
> 
>   app:
>     image: amruthpillai/reactive-resume:latest
>     restart: unless-stopped
>     ports:
>       - 3030:3000
>     depends_on:
>       - chrome
>       - minio
>       - postgres
>       - redis
>     environment:
>       # -- Environment Variables --
>       PORT: 3000
>       NODE_ENV: production
> 
>       # -- URLs --
>       PUBLIC_URL: http://server.example.com:3030
>       STORAGE_URL: http://server.example.com:9080/default/
> 
>       # -- Printer (Chrome) --
>       CHROME_TOKEN: chrome_token
>       CHROME_URL: ws://chrome:3000
> 
>       # -- Database (Postgres) --
>       DATABASE_URL: postgresql://postgres:postgres@postgres:5432/reactive_resumes
> 
>       # -- Auth --
>       ACCESS_TOKEN_SECRET: access_token_secret
>       REFRESH_TOKEN_SECRET: refresh_token_secret
> 
>       # -- Emails --
>       MAIL_FROM: resumes@example.com
>       SMTP_URL: smtp://email_user:email_password@email_server:587 # Optional
> 
>       # -- Storage (Minio) --
>       STORAGE_ENDPOINT: minio
>       STORAGE_PORT: 9000
>       STORAGE_REGION: us-east-1 # Optional
>       STORAGE_BUCKET: default
>       STORAGE_ACCESS_KEY: minioadmin
>       STORAGE_SECRET_KEY: minioadmin
>       STORAGE_USE_SSL: "false"
> 
>       # -- Cache (Redis) --
>       REDIS_URL: redis://default:password@redis:6379
> 
>       # -- Email --
>       # DISABLE_EMAIL_AUTH: true
> 
> volumes:
>   postgresql_data:
>     driver: local
>     driver_opts:
>       type: none
>       device: /opt/reactive_resume/postgresql_data
>       o: bind
>   minio_data:
>     driver: local
>     driver_opts:
>       type: none
>       device: /opt/reactive_resume/minio_data
>       o: bind
>   redis_data:
>     driver: local
>     driver_opts:
>       type: none
>       device: /opt/reactive_resume/redis_data
>       o: bind
> ```

Copy-pasting your exact docker-compose without changing anything, the app container fails to connect to the postgres database. Any ideas why this might be the case?

```
2024-01-16 10:39:24
 > @reactive-resume/source@4.0.3 prestart /app
2024-01-16 10:39:24
 > pnpm prisma:migrate
2024-01-16 10:39:24
 
2024-01-16 10:39:25
 
2024-01-16 10:39:25
 > @reactive-resume/source@4.0.3 prisma:migrate /app
2024-01-16 10:39:25
 > pnpm exec prisma migrate deploy
2024-01-16 10:39:25
 
2024-01-16 10:39:26
 Prisma schema loaded from tools/prisma/schema.prisma
2024-01-16 10:39:26
 Datasource "db": PostgreSQL database "reactive_resumes", schema "public" at "postgres:5432"
2024-01-16 10:39:26
 
2024-01-16 10:39:26
 Error: P1001: Can't reach database server at `postgres`:`5432`
2024-01-16 10:39:26
 
2024-01-16 10:39:26
 Please make sure your database server is running at `postgres`:`5432`.
2024-01-16 10:39:26
  ELIFECYCLE  Command failed with exit code 1.
2024-01-16 10:39:26
  ELIFECYCLE  Command failed with exit code 1.
```

**Comment by lytn1ng** [comment]
@Nachtschwingeswildhunt ,  
Unfortunately, I do not know what is causing the error for you. But I can confirm that it still works for me. 

I have this running on Ubuntu 23.04, if it matters at all.

**Comment by thermoweb** [comment]
@Nachtschwingeswildhunt If you still have an issue with that docker compose, here what I changed in the file to make it work in the 3080 ports (and 9080 for the minio):

```yaml
version: "3.8"

# In this Docker Compose example, it assumes that you maintain a reverse proxy externally (or chose not to).
# The only two exposed ports here are from minio (:9000) and the app itself (:3000).
# If these ports are changed, ensure that the env vars passed to the app are also changed accordingly.

services:
  # Database (Postgres)
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Storage (for image uploads)
  minio:
    image: minio/minio
    restart: unless-stopped
    command: server /data
    ports:
      - "9080:9000"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  # Chrome Browser (for printing and previews)
  chrome:
    image: ghcr.io/browserless/chromium:latest
    restart: unless-stopped
    environment:
      TIMEOUT: 10000
      CONCURRENT: 10
      TOKEN: chrome_token
      EXIT_ON_HEALTH_FAILURE: true
      PRE_REQUEST_HEALTH_CHECK: true

  app:
    image: amruthpillai/reactive-resume:latest
    restart: unless-stopped
    ports:
      - "3080:3000"
    depends_on:
      - postgres
      - minio
      - chrome
    environment:
      # -- Environment Variables --
      PORT: 3000
      NODE_ENV: production

      # -- URLs --
      PUBLIC_URL: https://localhost:3080
      STORAGE_URL: http://localhost:9080/default

      # -- Printer (Chrome) --
      CHROME_TOKEN: chrome_token
      CHROME_URL: ws://chrome:3000

      # -- Database (Postgres) --
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres

      # -- Auth --
      ACCESS_TOKEN_SECRET: access_token_secret
      REFRESH_TOKEN_SECRET: refresh_token_secret

      # -- Emails --
      MAIL_FROM: noreply@localhost
      # SMTP_URL: smtp://user:pass@smtp:587 # Optional

      # -- Storage (Minio) --
      STORAGE_ENDPOINT: minio
      STORAGE_PORT: 9000
      STORAGE_REGION: us-east-1 # Optional
      STORAGE_BUCKET: default
      STORAGE_ACCESS_KEY: minioadmin
      STORAGE_SECRET_KEY: minioadmin
      STORAGE_USE_SSL: false
      STORAGE_SKIP_BUCKET_CHECK: false

      # -- Crowdin (Optional) --
      # CROWDIN_PROJECT_ID:
      # CROWDIN_PERSONAL_TOKEN:

      # -- Email (Optional) --
      # DISABLE_SIGNUPS: false
      # DISABLE_EMAIL_AUTH: false

      # -- GitHub (Optional) --
      # GITHUB_CLIENT_ID: github_client_id
      # GITHUB_CLIENT_SECRET: github_client_secret
      # GITHUB_CALLBACK_URL: http://localhost:3000/api/auth/github/callback

      # -- Google (Optional) --
      # GOOGLE_CLIENT_ID: google_client_id
      # GOOGLE_CLIENT_SECRET: google_client_secret
      # GOOGLE_CALLBACK_URL: http://localhost:3000/api/auth/google/callback

volumes:
  minio_data:
  postgres_data:
```
