### ISSUE TITLE
[Bug] Link for documentation for local deployment?

### ISSUE THREAD

**Issue by justpankajdotcom** [AmruthPillai/Reactive-Resume#1683]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

I tried to search for documentation for local self-hosted deployment in both open and closed issues and found couple of links, however, they all redirect to 404 - Page not found. Is the address changed? I can see comments from author in other issues mentioning the below links as latest as april-may 2022. Is the address changed after that?

I cannot find any relevant links for deployment here --> [https://docs.rxresu.me/](https://docs.rxresu.me/)

[https://docs.rxresu.me/deployment/](https://docs.rxresu.me/deployment/) (This link mentioned by author in one of the issue for deployment doc doesn't work anymore)

### Expected Behavior

The link should direct to deployment page

### Steps To Reproduce

Go to [https://docs.rxresu.me/deployment/](https://docs.rxresu.me/deployment/)

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

None

**Comment by justpankajdotcom** [comment]
> I also couldn't find any recent/up-to-date docs, so I just thought for self-hosted option we'd probably have to figure it out ourselves by checking the [`tools/compose`](https://github.com/AmruthPillai/Reactive-Resume/tree/main/tools/compose) directory for examples, in combination with the [`.env.example`](https://github.com/AmruthPillai/Reactive-Resume/blob/main/.env.example). Still, some environment variables are not mentioned in the `.env.example` (like the one mentioned in #1640), so it's a bit of a puzzle to get it setup properly 🧩
> 
> Docs would definately help future users 👌

Yes, exactly. I tried with different setups but i cant get it working somehow. If you are also trying and haven't been able to yet. Shall we connect somewhere outside, like discord if it is okay for you? Maybe with collaboration it will become easier.

**Comment by ToshY** [comment]
Hey @justpankajdotcom 👋 

I've finally got it fully working yesterday evening locally 🙂 Sure, I'm open to discuss it on Discord (see my github profile for username) and share my `docker-compose.yml` and `.env.example` with you before posting it here.

**Comment by justpankajdotcom** [comment]
Hi @ToshY ,

Appreciate it. But I can't seem to search you there in discord with your username. Can you please check your privacy settings once?

**Comment by ToshY** [comment]
@justpankajdotcom Hmm my settings accept everything 🤔 Maybe I don't quite understand the new username system then; my legacy username is: ToshY#0823.

If that doesn't work, let's try the other way around and I'll send you a request.

**Comment by MelihDarcanxyz** [comment]
> Hey @justpankajdotcom 👋 
> 
> I've finally got it fully working yesterday evening locally 🙂 Sure, I'm open to discuss it on Discord (see my github profile for username) and share my `docker-compose.yml` and `.env.example` with you before posting it here.
> 
> 
> 

Can you please share it here so everyone can take advantage of it? Thanks in advance.

**Comment by ToshY** [comment]
Hey @MelihDarcanxyz 👋 

Sorry for the delayed response; I've been refining my setup the last couple of days to make it more production-friendly (with Traefik v2/v3). I'll post it in a couple of hours.

**Comment by N1KN1M** [comment]
The first section in CONTRIBUTING.md is about running the project locally. I've tried it but am facing errors on the last step

**Comment by craeckor** [comment]
If anyone here has issues with V3, here is my `docker-compose.yml`
```yaml
version: "3.8"

services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 15s
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secure_password

  server:
    image: amruthpillai/reactive-resume:server-3.8.4
    restart: always
    ports:
      - 3100:3100
    volumes:
      - ./assets/exports:/app/server/dist/assets/exports
      - ./assets/uploads:/app/server/dist/assets/uploads
    depends_on:
      - postgres
    environment:
      - PUBLIC_URL=http://localhost:3000
      - PUBLIC_SERVER_URL=http://localhost:3100/api
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secure_password
      - SECRET_KEY=secure_key_password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - JWT_SECRET=secure_jwt_password
      - JWT_EXPIRY_TIME=604800
      - STORAGE_S3_ENABLED=false
      - MAIL_FROM_NAME=Reactive Resume
      - MAIL_FROM_EMAIL=noreply@example.com
      - MAIL_HOST=mail.example.com
      - MAIL_PORT=587
      - MAIL_USERNAME=noreply@example.com
      - MAIL_PASSWORD=secure_mail_password
      - PDF_DELETION_TIME=10800

      
  client:
    image: amruthpillai/reactive-resume:client-3.8.4
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      - PUBLIC_URL=http://localhost:3000
      - PUBLIC_SERVER_URL=http://localhost:3100/api
      
volumes:
  pgdata:
  exports:
  uploads:
```
