### ISSUE TITLE
[Bug] Docker 'client-latest' and 'server-latest' tags not updated

### ISSUE THREAD

**Issue by samuraicow** [AmruthPillai/Reactive-Resume#1687]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Self-Hosted

### Current Behavior

'[client-latest](https://hub.docker.com/layers/amruthpillai/reactive-resume/client-latest/images/sha256-853f07b486a66b5549b6784c2aa034fa888409ffebfe53393aeb8f00ed0da590?context=explore)' and '[server-latest](https://hub.docker.com/layers/amruthpillai/reactive-resume/server-latest/images/sha256-5be7e61a2ff5ef50fbf9a3aa8bfc8b7aa7d6f26ea2c760b9e789596c6eb31e26?context=explore)' tags have not been updated for 4 months on Docker Hub.

### Expected Behavior

`docker pull amruthpillai/reactive-resume:client-latest` and `docker pull amruthpillai/reactive-resume:server-latest` should pull the latest versions.

### Steps To Reproduce

Using Marius Hosting's Docker compose script [link](https://mariushosting.com/how-to-install-reactive-resume-v3-on-your-synology-nas/):
```
version: "3.9"
services:
  resume-db:
    image: postgres
    container_name: RXRESUME-DB
    hostname: resume-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "reresume", "-U", "reresumeuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    user: 1026:100
    volumes:
      - /volume1/docker/rxv4/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: reresume
      POSTGRES_USER: reresumeuser
      POSTGRES_PASSWORD: reresumepw
    restart: always

  resume-server:
    image: amruthpillai/reactive-resume:server-latest
    container_name: RXRESUME-SERVER
    hostname: resume-server
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: curl -fSs http://localhost:3100/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - 8661:3100
    volumes:
      - /volume1/docker/rxv4/exports:/app/server/dist/assets/exports:rw
      - /volume1/docker/rxv4/uploads:/app/server/dist/assets/uploads:rw
    environment:
      - PUBLIC_URL=https://rxresume.yourname.synology.me
      - PUBLIC_SERVER_URL=https://rxresumeserver.yourname.synology.me
      - POSTGRES_DB=reresume
      - POSTGRES_USER=reresumeuser
      - POSTGRES_PASSWORD=reresumepw
      - SECRET_KEY=MariushostingMariushostingMari13
      - POSTGRES_HOST=resume-db
      - POSTGRES_PORT=5432
      - JWT_SECRET=MariushostingMariushostingMari13
      - JWT_EXPIRY_TIME=604800
      - MAIL_FROM_NAME=Reactive Resume
      - MAIL_FROM_EMAIL=Your-own-gmail-address
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=Your-own-gmail-address
      - MAIL_PASSWORD=Your-own-app-password
    restart: always
    depends_on:
      resume-db:
        condition: service_started

  resume-client:
    image: amruthpillai/reactive-resume:client-latest
    container_name: RXRESUME-CLIENT
    hostname: resume-client
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: curl -fSs 127.0.0.1:3000 || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - 8662:3000
    environment:
      - PUBLIC_URL=https://rxresume.yourname.synology.me
      - PUBLIC_SERVER_URL=https://rxresumeserver.yourname.synology.me
    restart: always
    depends_on:
      resume-server:
        condition: service_healthy
```

### What template are you using?

None
