### ISSUE TITLE
[Bug] ECONNREFUSED connecting to minio

### ISSUE THREAD

**Issue by danielkinahan** [AmruthPillai/Reactive-Resume#1689]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Self-Hosted

### Current Behavior

App can't connect to minio storage. I have changed the ports. 

```
/app/dist/apps/server/main.js:570

            throw new common_1.InternalServerErrorException(error);
...

    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.28.0.3',
    port: 3002
  },
  status: 500,
  options: {}
}
Node.js v20.10.0
 ELIFECYCLE  Command failed with exit code 1.
```

### Expected Behavior

Connection not refused. 200 return codes.

### Steps To Reproduce

1. Copy and modify the simple.yml docker compose file.
```yaml
version: "3.8"

services:
  # Database (Postgres)
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Storage (for image uploads)
  minio:
    image: minio/minio
    restart: unless-stopped
    command: server /data
    ports:
      - 3002:9000
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  # Chrome Browser (for printing and previews)
  chrome:
    image: browserless/chrome:1.61.0-puppeteer-21.4.1
    restart: unless-stopped
    environment:
      TOKEN: chrome_token
      EXIT_ON_HEALTH_FAILURE: "true"
      PRE_REQUEST_HEALTH_CHECK: "true"

  # Redis (for cache & server session management)
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --requirepass password

  app:
    image: amruthpillai/reactive-resume:latest
    restart: unless-stopped
    ports:
      - 3001:3000
    depends_on:
      - postgres
      - minio
      - redis
      - chrome
    environment:
      # -- Environment Variables --
      PORT: 3001
      NODE_ENV: production

      # -- URLs --
      PUBLIC_URL: http://localhost:3001
      STORAGE_URL: http://localhost:3002

      # -- Printer (Chrome) --
      CHROME_TOKEN: chrome_token
      CHROME_URL: ws://chrome:3001

      # -- Database (Postgres) --
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres

      # -- Auth --
      ACCESS_TOKEN_SECRET: access_token_secret
      REFRESH_TOKEN_SECRET: refresh_token_secret

      # -- Emails --
      MAIL_FROM: noreply@localhost
      # SMTP_URL: smtp://user:pass@smtp:587 # Optional

      # -- Storage (Minio) --
      STORAGE_ENDPOINT: minio
      STORAGE_PORT: 3002
      STORAGE_REGION: us-east-1 # Optional
      STORAGE_BUCKET: default
      STORAGE_ACCESS_KEY: minioadmin
      STORAGE_SECRET_KEY: minioadmin
      STORAGE_USE_SSL: "false"

      # -- Cache (Redis) --
      REDIS_URL: redis://default:password@redis:6379

volumes:
  minio_data:
  postgres_data:
```
2. docker-compose up -d

### What template are you using?

None

### Anything else?

I'm sure there is something I'm doing wrong here but couldn't find any documentation about how these env vars are used.
