### ISSUE TITLE
[Bug] Route `/artboard` is always publicly available; requires bypassing Traefik rule

### ISSUE THREAD

**Issue by ToshY** [AmruthPillai/Reactive-Resume#1695]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me/) / Self-Hosted

### Current Behavior

The route prefix `/artboard` _always_ needs to be publicely available in order for the chrome service to be able to create previews/PDFs. But it is also used for the builder in the frontend.

In a self-hosted production setting this now poses a security problem as I do not want the application to be available to the outside world. Normally, Traefik middleware can be used to limit the access to the application, but as the `/artboard` needs to be available, it now requires an additional bypass rule.

```yml
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.reactive-resume.tls: true
      traefik.http.routers.reactive-resume.entrypoints: websecure
      traefik.http.routers.reactive-resume.rule: Host(`resume.example.com`)
      traefik.http.routers.reactive-resume.service: reactive-resume
      # Middleware (oidc) to prevent unwanted access to the application
      traefik.http.routers.reactive-resume.middlewares: oidc@file
      traefik.http.services.reactive-resume.loadbalancer.server.port: 3000
      # Bypass `/artboard` route which is required for chrome container to generate previews and PDFs
      traefik.http.routers.reactive-resume-bypass.tls: true
      traefik.http.routers.reactive-resume-bypass.entrypoints: websecure
      traefik.http.routers.reactive-resume-bypass.rule: Host(`resume.example.com`) && PathPrefix(`/artboard`)
      traefik.http.routers.reactive-resume-bypass.service: reactive-resume-bypass
      traefik.http.services.reactive-resume-bypass.loadbalancer.server.port: 3000
```

So now the `resume.example.com/artboard` is publicely available, without the need for any authentication whatsoever, as the middleware was bypassed.

### Expected Behavior

* The `/artboard` route should _not_ be able to be accessed without being logged-in from the frontend.
* The `/artboard` route should be able to be accessed from the chrome container to be able to generate previews/PDFs.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What template are you using?

None

### Anything else?

The following routes are available without being logged-in in cloud as well:

* https://rxresu.me/artboard/builder
* https://rxresu.me/artboard/preview
