### ISSUE TITLE
[Bug] Can't download PDF

### ISSUE THREAD

**Issue by cacpmw** [AmruthPillai/Reactive-Resume#1719]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Self-Hosted

### Current Behavior

I can't export as PDF or JSON for that matter

### Expected Behavior

To be able to export as pdf

### Steps To Reproduce

1. Access the public profile
1. Click on DOWNLOAD PDF
1. It tries to load but it times out

This is what I get:

```json
{
"statusCode":504,
"timestamp":"2024-01-18T13:49:23.220Z",
"path":"/printer/user/my-resume-?lastUpdated=1705583875"
}
```

Here is my docker compose
```yaml
  reactiveresume-api:
    image: amruthpillai/reactive-resume:server-latest
    restart: unless-stopped
    pull_policy: always
    container_name: reactiveresume-api
    ports:
      - 1021:3100
    depends_on:
      - reactiveresume-db
    env_file: ./Volumes/Reactiveresume/Api/.env

  reactiveresume-db:
    image: postgres:alpine
    restart: unless-stopped
    pull_policy: always
    container_name: reactiveresume-db
    volumes:
      - ./Volumes/Reactiveresume/Database/Data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 15s
      interval: 30s
      timeout: 30s
      retries: 3
    env_file: ./Volumes/Reactiveresume/Database/.env

  reactiveresume-client:
    image: amruthpillai/reactive-resume:client-latest
    container_name: reactiveresume-client
    restart: unless-stopped
    pull_policy: always
    ports:
      - 1022:3000
    depends_on:
      - reactiveresume-api
    env_file: ./Volumes/Reactiveresume/Client/.env
```
```.env

#Client .env
PUBLIC_URL=http://192.168.88.182:1022
PUBLIC_SERVER_URL=http://192.168.88.182:1021

#Api .env
POSTGRES_DB=reactiveresume
POSTGRES_USER=**********
POSTGRES_PASSWORD=******
PUBLIC_URL=http://192.168.88.182:1022
PUBLIC_SERVER_URL=http://192.168.88.182:1021
SECRET_KEY=jYudtPFoJTCxZWu4Gstx6FjvYLGewLgwDqVen6UfF3sGUoc6mYVfuPi8zXTxx8k4kpqDiCVduF8n3kDDtPyxpjMWc3qKexsML7SMRBNNVnVuk3Q2DHcxyYxNArwEDcS3
POSTGRES_HOST=reactiveresume-db
POSTGRES_PORT=5432
JWT_SECRET=ndgjSuDtghRLrW6ZJ59rRG2N7nFiqJGi7JJFrqPvvSHLsLRSXHTGEzWGzKceRRCaV4nQaj8mhPfWEhLD7LZSJdeVGDD3qg46tNd8VJwDYzp6x6Td9zDaBFeL6Tj2JjNJ
JWT_EXPIRY_TIME=604800


### What browsers are you seeing the problem on?

Firefox

### What template are you using?

None

### Anything else?

_No response_
