### ISSUE TITLE
[Bug] Docker container return puppeteer error when trying to download as pdf

### ISSUE THREAD

**Issue by bxlinfman** [AmruthPillai/Reactive-Resume#1793]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Self-Hosted

### Current Behavior

After creating my resume, I click on the export as pdf button. The browser shows at it loads then it opens an empty tab and the docker console returns this error : 

```
  Trace: Error [TypeError]: Cannot read properties of null (reading 'cloneNode')
  
      at evaluate (evaluate at processPage (/app/dist/apps/server/main.js:13202:45), <anonymous>:1:50)
  
      at #evaluate (/app/node_modules/.pnpm/puppeteer-core@21.7.0/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:221:55)
  
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  
      at async ExecutionContext.evaluate (/app/node_modules/.pnpm/puppeteer-core@21.7.0/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:116:16)
  
      at async IsolatedWorld.evaluate (/app/node_modules/.pnpm/puppeteer-core@21.7.0/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:123:16)
  
      at async CdpFrame.evaluate (/app/node_modules/.pnpm/puppeteer-core@21.7.0/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:353:20)
  
      at async CdpPage.evaluate (/app/node_modules/.pnpm/puppeteer-core@21.7.0/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:741:20)
  
      at async processPage (/app/dist/apps/server/main.js:13202:34)
  
      at async PrinterService.generateResume (/app/dist/apps/server/main.js:13215:17)
  
      at async /app/dist/apps/server/main.js:13140:25
  
      at PrinterService.generateResume (/app/dist/apps/server/main.js:13246:21)
  
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  
      at async /app/dist/apps/server/main.js:13140:25
  
      at async UtilsService.getCachedOrSet (/app/dist/apps/server/main.js:11902:23)
  
      at async ResumeService.printResume (/app/dist/apps/server/main.js:13985:21)
  
      at async ResumeController.printResume (/app/dist/apps/server/main.js:13600:25)
```

### Expected Behavior

there should be a popup to select where to store the pdf export

### Steps To Reproduce

My docker compose script is as follows (I'm using the simple.yml from your github): 

```
version: "3.8"

# In this Docker Compose example, it assumes that you maintain a reverse proxy externally (or chose not to).
# The only two exposed ports here are from minio (:9000) and the app itself (:3000).
# If these ports are changed, ensure that the env vars passed to the app are also changed accordingly.

services:
  # Database (Postgres)
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - /volume1/docker/rxv4/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Storage (for image uploads)
  minio:
    image: minio/minio
    restart: on-failure:5
    command: server /data
    ports:
      - 9753:9000
    volumes:
      - /volume1/docker/rxv4/data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  # Chrome Browser (for printing and previews)
  chrome:
    image: browserless/chrome:1.61.0-puppeteer-21.4.1
    restart: on-failure:5
    environment:
      TOKEN: chrome_token
      EXIT_ON_HEALTH_FAILURE: true
      PRE_REQUEST_HEALTH_CHECK: true

  # Redis (for cache & server session management)
  redis:
    image: redis:alpine
    restart: on-failure:5
    command: redis-server --requirepass redispass
    container_name: Resume-REDIS
    hostname: resume-redis
    user: 1026:100
    volumes:
      - /volume1/docker/rxv4/redis:/data:rw
    environment:
      TZ: Europe/Brussels
    restart: on-failure:5

  app:
    image: amruthpillai/reactive-resume:latest
    restart: on-failure:5
    ports:
      - 9751:3000
    depends_on:
      - postgres
      - minio
      - redis
      - chrome
    environment:
      # -- Environment Variables --
      PORT: 3000
      NODE_ENV: production

      # -- URLs --
      PUBLIC_URL: <reverse proxy url>/ 
      STORAGE_URL: <reverse proxy url for storage>

      # -- Printer (Chrome) --
      CHROME_TOKEN: chrome_token
      CHROME_URL: ws://chrome:3000

      # -- Database (Postgres) --
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres

      # -- Auth --
      ACCESS_TOKEN_SECRET: access_token_secret
      REFRESH_TOKEN_SECRET: refresh_token_secret

      # -- Emails --
      MAIL_FROM: noreply@localhost
      SMTP_URL: <my smtp url>

      # -- Storage (Minio) --
      STORAGE_ENDPOINT: minio
      STORAGE_PORT: 9000
      STORAGE_REGION: us-east-1 # Optional
      STORAGE_BUCKET: default
      STORAGE_ACCESS_KEY: minioadmin
      STORAGE_SECRET_KEY: minioadmin
      STORAGE_USE_SSL: false

      # -- Cache (Redis) --
      REDIS_URL: redis://default:password@redis:6379

      # -- Sentry --
      # VITE_SENTRY_DSN: https://id.sentry.io # Optional

      # -- Crowdin (Optional) --
      # CROWDIN_PROJECT_ID:
      # CROWDIN_PERSONAL_TOKEN:

      # -- Email (Optional) --
      # DISABLE_EMAIL_AUTH: true
      # VITE_DISABLE_SIGNUPS: true

      # -- GitHub (Optional) --
      GITHUB_CLIENT_ID: github_client_id
      GITHUB_CLIENT_SECRET: github_client_secret
      GITHUB_CALLBACK_URL: http://localhost:3000/api/auth/github/callback

      # -- Google (Optional) --
      GOOGLE_CLIENT_ID: google_client_id
      GOOGLE_CLIENT_SECRET: google_client_secret
      GOOGLE_CALLBACK_URL: http://localhost:3000/api/auth/google/callback

volumes:
  minio_data:
  postgres_data:
```

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### What template are you using?

None

### Anything else?

This is an amazing tool, I hope to use it fully soon !
