### ISSUE TITLE
PDF exports as 1 long page.

### ISSUE THREAD

**Issue by insidiousdog** [AmruthPillai/Reactive-Resume#1867]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Self-Hosted

### Current Behavior

Exporting to a pdf, the pdf renders successfully and downloads, but the page breaks don't carry across. This results in a Page 1 of 1 pdf, with none of the separations in the editor being reflected in the rendered document.

### Expected Behavior

The pdf output is multi page.

### Steps To Reproduce

1. Go to Export.
2. Click PDF icon.
3. Open downloaded PDF.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What template are you using?

None

### Anything else?

My compose file:

```
version: "3.8"
services:
  Database (Postgres)
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  Storage (for image uploads)
  minio:
    image: minio/minio
    restart: unless-stopped
    command: server /data
    ports:
      - 9000:9000
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  Chrome Browser (for printing and previews)
  chrome:
    image: ghcr.io/browserless/chromium:latest
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      TIMEOUT: 10000
      CONCURRENT: 10
      TOKEN: chrome_token
      EXIT_ON_HEALTH_FAILURE: true
      PRE_REQUEST_HEALTH_CHECK: true

  Redis (for cache & server session management)
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --requirepass password

  app:
    image: amruthpillai/reactive-resume:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - minio
      - redis
      - chrome
    environment:
      -- Environment Variables --
      PORT: 3000
      NODE_ENV: production

      -- URLs --
      PUBLIC_URL: http://<my server local ip address>:3000
      STORAGE_URL: http://<my server local ip address>:9000/default

      -- Printer (Chrome) --
      CHROME_TOKEN: chrome_token
      CHROME_URL: ws://chrome:3000

      -- Database (Postgres) --
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres

      -- Auth --
      ACCESS_TOKEN_SECRET: access_token_secret
      REFRESH_TOKEN_SECRET: refresh_token_secret

      -- Emails --
      MAIL_FROM: noreply@localhost
      SMTP_URL: smtp://user:pass@smtp:587 # Optional

      -- Storage (Minio) --
      STORAGE_ENDPOINT: minio
      STORAGE_PORT: 9000
      STORAGE_REGION: us-east-1 # Optional
      STORAGE_BUCKET: default
      STORAGE_ACCESS_KEY: minioadmin
      STORAGE_SECRET_KEY: minioadmin
      STORAGE_USE_SSL: false

      -- Cache (Redis) --
      REDIS_URL: redis://default:password@redis:6379

      -- Sentry --
      VITE_SENTRY_DSN: https://id.sentry.io # Optional

      -- Crowdin (Optional) --
      CROWDIN_PROJECT_ID:
      CROWDIN_PERSONAL_TOKEN:

      -- Email (Optional) --
      DISABLE_EMAIL_AUTH: true
      VITE_DISABLE_SIGNUPS: true

volumes:
  minio_data:
  postgres_data:
```
