### ISSUE TITLE
Argument of type is not assignable to  parameter of type 'number | undefined'.

### ISSUE THREAD

**Issue by LayersOfAbstraction** [AmruthPillai/Reactive-Resume#1881]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Self-Hosted

### Current Behavior

I recently deleted my local repo then forked and cloned the latest version, using the existing Postgres Docker container so I can restore my existing resumes from that (I got docker volume backups). When I run:

```
pnpm dev
```

I get this error:
```bash
ERROR in ./apps/server/src/storage/storage.service.ts:147:66
TS2345: Argument of type '{ "Content-Type": string; "Content-Disposition"?: undefined; } | { "Content-Type": string; "Content-Disposition": string; }' is not assignable to 
parameter of type 'number | undefined'.
  Type '{ "Content-Type": string; "Content-Disposition"?: undefined; }' is not assignable to type 'number'.
    145 |
    146 |       await Promise.all([
  > 147 |         this.client.putObject(this.bucketName, filepath, buffer, metadata),
        |                                                                  ^^^^^^^^
    148 |         this.redis.set(`user:${userId}:storage:${type}:${filename}`, url),
    149 |       ]);
    150 |
webpack compiled with 2 errors (0f9585d12bb04858)
Build failed, waiting for changes to restart...
```
Here is the full stack trace if it helps. 

```

> @reactive-resume/source@4.0.11 dev /home/jords/Reactive-Resume
> nx run-many -t serve


 NX   Running target serve for 3 projects:

- artboard
- client
- server

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

> nx run artboard:serve:development


> nx run client:serve:development


> nx run server:serve:development

  ➜  Local:   http://localhost:6173/artboard/
  ➜  Network: http://172.29.139.179:6173/artboard/
Loading proxy configuration from: /home/jords/Reactive-Resume/apps/client/proxy.conf.json
  ➜  Local:   http://localhost:5173/
  ➜  Network: http://172.29.139.179:5173/
chunk (runtime: main) main.js (main) 649 KiB [entry] [rendered]
ERROR in ./apps/server/src/storage/storage.service.ts:58:5
TS2322: Type 'import("/home/jords/Reactive-Resume/node_modules/.pnpm/minio@7.1.4/node_modules/minio/dist/main/minio").Client' is not assignable to type 'import("/home/jords/Reactive-Resume/node_modules/.pnpm/minio@8.0.0/node_modules/minio/dist/main/minio").Client'.
  Types of property 'composeObject' are incompatible.
    Type '{ (destObjConfig: import("/home/jords/Reactive-Resume/node_modules/.pnpm/minio@7.1.4/node_modules/minio/dist/main/helpers").CopyDestinationOptions, sourceObjList: import("/home/jords/Reactive-Resume/node_modules/.pnpm/minio@7.1.4/node_modules/minio/dist/main/helpers").CopySourceOptions[], callback: import("/home/jor...' is not assignable to type '{ (destObjConfig: import("/home/jords/Reactive-Resume/node_modules/.pnpm/minio@8.0.0/node_modules/minio/dist/main/helpers").CopyDestinationOptions, sourceObjList: import("/home/jords/Reactive-Resume/node_modules/.pnpm/minio@8.0.0/node_modules/minio/dist/main/helpers").CopySourceOptions[], callback: import("/home/jor...'.       
      Types of parameters 'destObjConfig' and 'destObjConfig' are incompatible.
        Type 'import("/home/jords/Reactive-Resume/node_modules/.pnpm/minio@8.0.0/node_modules/minio/dist/main/helpers").CopyDestinationOptions' is not assignable to type 'import("/home/jords/Reactive-Resume/node_modules/.pnpm/minio@7.1.4/node_modules/minio/dist/main/helpers").CopyDestinationOptions'.
          Types have separate declarations of a private property 'Encryption'.
    56 |
    57 |   async onModuleInit() {
  > 58 |     this.client = this.minioService.client;
       |     ^^^^^^^^^^^
    59 |     this.bucketName = this.configService.getOrThrow<string>("STORAGE_BUCKET");
    60 |     this.skipCreateBucket = this.configService.getOrThrow<boolean>("STORAGE_SKIP_CREATE_BUCKET");
    61 |
ERROR in ./apps/server/src/storage/storage.service.ts:147:66
TS2345: Argument of type '{ "Content-Type": string; "Content-Disposition"?: undefined; } | { "Content-Type": string; "Content-Disposition": string; }' is not assignable to 
parameter of type 'number | undefined'.
  Type '{ "Content-Type": string; "Content-Disposition"?: undefined; }' is not assignable to type 'number'.
    145 |
    146 |       await Promise.all([
  > 147 |         this.client.putObject(this.bucketName, filepath, buffer, metadata),
        |                                                                  ^^^^^^^^
    148 |         this.redis.set(`user:${userId}:storage:${type}:${filename}`, url),
    149 |       ]);
    150 |
webpack compiled with 2 errors (0f9585d12bb04858)
Build failed, waiting for changes to restart...
```

### Expected Behavior

I expected it to compile and allow me to navigate to my local URL and pull data from container.

### Steps To Reproduce

1. Clone project repo.
2. Edit the compose file to have this"

```yaml
version: "3.8"

# In this Docker Compose example, it assumes that you maintain a reverse proxy externally (or chose not to).
# The only two exposed ports here are from minio (:9000) and the app itself (:3000).
# If these ports are changed, ensure that the env vars passed to the app are also changed accordingly.

services:
  # Database (Postgres)
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Storage (for image uploads)
  minio:
    image: minio/minio
    restart: unless-stopped
    command: server /data
    ports:
      - 9000:9000
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  # Chrome Browser (for printing and previews)
    # Chrome Browser (for printing and previews)
  chrome:
    image: ghcr.io/browserless/chromium:latest
    restart: unless-stopped
    environment:
      TIMEOUT: 10000
      CONCURRENT: 10
      TOKEN: chrome_token
      EXIT_ON_HEALTH_FAILURE: true
      PRE_REQUEST_HEALTH_CHECK: true

  # Redis (for cache & server session management)
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --requirepass password

  app:
    image: amruthpillai/reactive-resume:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - minio
      - redis
      - chrome
    environment:
      # -- Environment Variables --
      PORT: 3000
      NODE_ENV: production

      # -- URLs --
      PUBLIC_URL: http://localhost:3000
      STORAGE_URL: http://localhost:9000/default

      # -- Printer (Chrome) --
      CHROME_TOKEN: chrome_token
      CHROME_URL: ws://chrome:3000

      # -- Database (Postgres) --
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres

      # -- Auth --
      ACCESS_TOKEN_SECRET: access_token_secret
      REFRESH_TOKEN_SECRET: refresh_token_secret

      # -- Emails --
      MAIL_FROM: noreply@localhost
      # SMTP_URL: smtp://user:pass@smtp:587 # Optional

      # -- Storage (Minio) --
      STORAGE_ENDPOINT: minio
      STORAGE_PORT: 9000
      STORAGE_REGION: us-east-1 # Optional
      STORAGE_BUCKET: default
      STORAGE_ACCESS_KEY: minioadmin
      STORAGE_SECRET_KEY: minioadmin
      STORAGE_USE_SSL: false

      # -- Cache (Redis) --
      REDIS_URL: redis://default:password@redis:6379

      # -- Sentry --
      # VITE_SENTRY_DSN: https://id.sentry.io # Optional

      # -- Crowdin (Optional) --
      # CROWDIN_PROJECT_ID:
      # CROWDIN_PERSONAL_TOKEN:

      # -- Email (Optional) --
      # DISABLE_EMAIL_AUTH: true
      # VITE_DISABLE_SIGNUPS: true

      # -- GitHub (Optional) --
      GITHUB_CLIENT_ID: github_client_id
      GITHUB_CLIENT_SECRET: github_client_secret
      GITHUB_CALLBACK_URL: http://localhost:3000/api/auth/github/callback

      # -- Google (Optional) --
      GOOGLE_CLIENT_ID: google_client_id
      GOOGLE_CLIENT_SECRET: google_client_secret
      GOOGLE_CALLBACK_URL: http://localhost:3000/api/auth/google/callback

volumes:
  minio_data:
  postgres_data:
```

3. Run through the normal steps as shown in the repo's [CONTRIBUTING.md](https://github.com/AmruthPillai/Reactive-Resume/blob/main/CONTRIBUTING.md) file except run `docker compose up` in your console instead of the compose command in the CONTRIBUTING file. I ran this so I could use my current docker container. Doesn't work even if I use a new container.

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

None

### Anything else?

If anyone is on a version that can download resume files as .pdf and doesn't have errors doing that, please let me know which previous commit you are on. The updated browser didn't work from last year's version of the Reactive Resume app. Thank you.
