### ISSUE TITLE
Timed out error when download PDF 

### ISSUE THREAD

**Issue by JiangLongLiu** [AmruthPillai/Reactive-Resume#1895]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Self-Hosted

### Current Behavior

I am deployed in the Docker of NAS.

## my configuration file 
``` yml
version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: Resume-DB
    hostname: resume-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "resume", "-U", "resumeuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /root/docker/resume/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: resume
      POSTGRES_USER: resumeuser
      POSTGRES_PASSWORD: 123456
    restart: on-failure:5

  minio:
    image: quay.io/minio/minio:latest
    command: server /data
    container_name: Resume-MINIO
    hostname: resume-minio
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 9753:9000
    volumes:
      - /root/docker/resume/data:/data:rw
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: 123456
      TIMEOUT: 50000
    restart: on-failure:5

  chrome:
    image: browserless/chrome:1-puppeteer-16.2.0
    container_name: Resume-CHROME
    hostname: chrome
    mem_limit: 4g
    extra_hosts:
      - host.docker.internal:host-gateway
    cpu_shares: 768
    user: 1026:100
    environment:
      TOKEN: chrome_token
      EXIT_ON_HEALTH_FAILURE: false
      PRE_REQUEST_HEALTH_CHECK: false
      TIMEOUT: 50000
    restart: on-failure:5
    
  resume:
    image: amruthpillai/reactive-resume:latest
    container_name: Resume-ACCESS
    hostname: resume
    restart: on-failure:5
    mem_limit: 6g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    ports:
      - 9751:3000
    environment:
      TZ: Asia/Shanghai
      PORT: 3000
      NODE_ENV: production
      SECRET_KEY: b48ekrdrgEEX4jngKx4KIYT3UiVAgOKsvaWnnglvB5o=
      ACCESS_TOKEN_SECRET: access_token_secret
      REFRESH_TOKEN_SECRET: refresh_token_secret
      PUBLIC_URL: https://resume.yourdomain.com:8829    # 9751-->8829
      STORAGE_URL: https://download.yourdomain.com:8809/default # 8753-->8809
      CHROME_TOKEN: chrome_token
      CHROME_URL: ws://chrome:3000
      DATABASE_URL: postgresql://resumeuser:123456@resume-db:5432/resume
      STORAGE_ENDPOINT: minio
      STORAGE_PORT: 9000
      STORAGE_REGION: us-east-1
      STORAGE_BUCKET: default
      STORAGE_ACCESS_KEY: minioadmin
      STORAGE_SECRET_KEY: 123456
      STORAGE_USE_SSL: false 
      DISABLE_EMAIL_AUTH: false
      VITE_DISABLE_SIGNUPS: false
      TIMEOUT: 50000
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      chrome:
        condition: service_started
```
##  Resume-ACCESS error message

[Nest] 87  - 05/14/2024, 5:24:53 PM     LOG [PrinterService] Retrying to generate preview of resume #clw66rxri00031tkwtbqtu22m, attempt #1
**Trace: TimeoutError: Navigation timeout of 30000 ms exceeded**
    at new Deferred (/app/node_modules/.pnpm/puppeteer-core@22.8.0/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:59:34)
    at Deferred.create (/app/node_modules/.pnpm/puppeteer-core@22.8.0/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:21:16)
    at new LifecycleWatcher (/app/node_modules/.pnpm/puppeteer-core@22.8.0/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/LifecycleWatcher.js:66:60)
    at CdpFrame.goto (/app/node_modules/.pnpm/puppeteer-core@22.8.0/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Frame.js:136:29)
    at CdpFrame.<anonymous> (/app/node_modules/.pnpm/puppeteer-core@22.8.0/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:98:27)
    at CdpPage.goto (/app/node_modules/.pnpm/puppeteer-core@22.8.0/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:585:43)
    at PrinterService.generateResume (/app/dist/apps/server/main.js:13097:24)
    at async PrinterService.printResume (/app/dist/apps/server/main.js:13044:21)
    at async ResumeService.printResume (/app/dist/apps/server/main.js:13841:21)
    at async ResumeController.printResume (/app/dist/apps/server/main.js:13488:25)
    at PrinterService.generateResume (/app/dist/apps/server/main.js:13149:21)
    at async PrinterService.printResume (/app/dist/apps/server/main.js:13044:21)
    at async ResumeService.printResume (/app/dist/apps/server/main.js:13841:21)
    at async ResumeController.printResume (/app/dist/apps/server/main.js:13488:25)

### Steps To Reproduce

1. Create and establish
2. Do not modify any font
3. Click the download button to download the PDF
4. After waiting for 10 seconds, another empty tab opened. There aren't any pdfs.
### What browsers are you seeing the problem on?

Chrome

### What template are you using?

None

### Anything else?
I noticed that avatars can be uploaded and avatars can be loaded normally. This indicates that there is no problem accessing the storage system.

Could it be an error caused by not generating the pdf and then loading the pdf?

**Comment by jeremyyin2012** [comment]
I found a solution:

1. Open Sharing: toggle Public On, copy URL, open in new tab
2. Print to PDF: click Three-dot menu on top right, click Print, choose Save as PDF, Save. (Ctrl/Command + P)
3. Close Sharing: toggle Public Off !!!

PS: If we had a guide to a private preview page, it would be easy to indirectly solve this problem of exporting PDF and significantly reduce resource consumption.

**Comment by JiangLongLiu** [comment]
It's a network problem. Because both chrome and resume containers need to access some websites when generating PDF.


My solution is to add proxies to the two containers, chrome and resume, for example：
```
    environment:
      HTTP_PROXY: http://192.168.1.6:1080
      HTTPS_PROXY: http://192.168.1.6:1080
      NO_PROXY: "localhost,127.0.0.1,192.168.1.*"
```
After I added the proxy to these two containers, the PDF can be downloaded smoothly.
