### ISSUE TITLE
[Bug] Can no longer use `DEFAULT_IGNORE_HTTPS_ERRORS` for  `browserless/chromium` 2 causing `net::ERR_CERT_AUTHORITY_INVALID`

### ISSUE THREAD

**Issue by ToshY** [AmruthPillai/Reactive-Resume#1897]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Self-Hosted

### Current Behavior

In [v4.0.9](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v4.0.9) the stack was changed to use `browserless/chromium` v2, which no longer allows for certain environment variables that could be used in V1, like `DEFAULT_IGNORE_HTTPS_ERRORS`: https://docs.browserless.io/migrate/#removed-parameters-no-replacements

This causes my stack to break, as it now no longer generates previews and throws `net::ERR_CERT_AUTHORITY_INVALID` when testing locally.

```text
chrome-1           | 2024-05-14T20:31:45.364944574Z   puppeteer:protocol:RECV ◀   '{"method":"Network.requestWillBeSent","params":{"requestId":"0A603AF2E5BBF067D2DE59212E0148F7","loaderId":"0A603AF2E5BBF067D2DE59212E0148F7","doc
umentURL":"https://resume.example.com/artboard/preview","request":{"url":"https://resume.example.com/artboard/preview","method":"GET","headers":{"Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit
/537.36 (KHTML, like Gecko) HeadlessChrome/124.0.0.0 Safari/537.36","sec-ch-ua":"\\"Not-A.Brand\\";v=\\"99\\", \\"Chromium\\";v=\\"124\\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\\"Linux\\""},"mixedContentType":"none","in
itialPriority":"VeryHigh","referrerPolicy":"strict-origin-when-cross-origin","isSameSite":true},"timestamp":11743.615519,"wallTime":1715718705.364352,"initiator":{"type":"other"},"redirectHasExtraInfo":false,"type":"Document","frameId":"AF73F2D7C39A6F2E6CAE1E6E78884EE2","hasUserGesture":false},"sessionId":"DFCC747308115B18FC98870560BC649E"}'
chrome-1           | 2024-05-14T20:31:45.364959342Z   puppeteer:protocol:RECV ◀ ] +0ms
chrome-1           | 2024-05-14T20:31:45.375526033Z   puppeteer:protocol:RECV ◀ [
chrome-1           | 2024-05-14T20:31:45.375545429Z   puppeteer:protocol:RECV ◀   '{"method":"Network.loadingFailed","params":{"requestId":"0A603AF2E5BBF067D2DE59212E0148F7","timestamp":11743.626045,"type":"Document","errorText":"net::ERR_CERT_AUTHORITY_INVALID","canceled":false},"sessionId":"DFCC747308115B18FC98870560BC649E"}'
chrome-1           | 2024-05-14T20:31:45.375548896Z   puppeteer:protocol:RECV ◀ ] +0ms
reactive-resume-1  | 2024-05-14T20:31:45.588127914Z [Nest] 85  - 05/14/2024, 8:31:45 PM   ERROR Error: net::ERR_CERT_AUTHORITY_INVALID at https://resume.example.com/artboard/preview
```

The main difference with [existing examples](https://github.com/AmruthPillai/Reactive-Resume/tree/main/tools/compose), is that instead of exposing the printer container service, I'm using the internal connection for the chrome URL: `ws://chrome:3000`. This worked fine with V1 but no longer in V2.

### Expected Behavior

Being able to use `ws://chrome:3000` again instead of exposing the container, possibly by allowing additional options to be passed to `puppeteer.connect`.

https://github.com/AmruthPillai/Reactive-Resume/blob/7a8b5d09c642a0870c24843825fa5ceb8b9247a8/apps/server/src/printer/printer.service.ts#L33

### Steps To Reproduce

<details><summary><code>.env</code></summary>
<p>

```dotenv
###> Image versions ###
REACTIVE_RESUME_IMAGE_VERSION="v4.1.2"
BROWSERLESS_CHROME_IMAGE_VERSION="v2.8.0"
POSTGRES_IMAGE_VERSION="15-alpine"
###< Image versions ###

###> App ###
APP_DOMAIN="example.com"
###< App ###

###> Postgres ###
POSTGRES_HOST="postgres"
POSTGRES_PORT="5432"
POSTGRES_DATABASE="rxresume"
POSTGRES_USER=""
POSTGRES_PASSWORD=""
###< Postgres ###

###> Chrome ###
BROWSERLESS_CHROME_TOKEN=""
BROWSERLESS_EXIT_ON_HEALTH_FAILURE="true"
BROWSERLESS_HEALTH="true"
# No longer working in V2 of browserless/chromium
# BROWSERLESS_CHROME_DEFAULT_IGNORE_HTTPS_ERRORS="true"
### < Chrome ###

###> Reactive Resume ###
REACTIVE_RESUME_TZ="UTC"
REACTIVE_RESUME_NODE_ENV="production"
# Application will be available at `resume.example.com`; change this to your liking
REACTIVE_RESUME_PUBLIC_URL="https://resume.${APP_DOMAIN}"
REACTIVE_RESUME_DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}"
REACTIVE_RESUME_ACCESS_TOKEN_SECRET=""
REACTIVE_RESUME_REFRESH_TOKEN_SECRET=""
REACTIVE_RESUME_CHROME_URL="ws://chrome:3000"
REACTIVE_RESUME_SMTP_URL=
REACTIVE_RESUME_MAIL_FROM="noreply@${APP_DOMAIN}"
REACTIVE_RESUME_STORAGE_PORT=
REACTIVE_RESUME_STORAGE_REGION=
REACTIVE_RESUME_STORAGE_BUCKET=
REACTIVE_RESUME_STORAGE_ACCESS_KEY=
REACTIVE_RESUME_STORAGE_SECRET_KEY=
REACTIVE_RESUME_STORAGE_USE_SSL="false"
REACTIVE_RESUME_STORAGE_ENDPOINT=
REACTIVE_RESUME_SKIP_STORAGE_BUCKET_CHECK="true"
REACTIVE_RESUME_STORAGE_URL=
REACTIVE_RESUME_VITE_SENTRY_DSN=
REACTIVE_RESUME_CROWDIN_PROJECT_ID=
REACTIVE_RESUME_CROWDIN_PERSONAL_TOKEN=
REACTIVE_RESUME_DISABLE_EMAIL_AUTH="TRUE"
REACTIVE_RESUME_VITE_DISABLE_SIGNUPS="TRUE"
REACTIVE_RESUME_GITHUB_CLIENT_ID=
REACTIVE_RESUME_GITHUB_CLIENT_SECRET=
# ${REACTIVE_RESUME_PUBLIC_URL}/api/auth/github/callback
REACTIVE_RESUME_GITHUB_CALLBACK_URL=
REACTIVE_RESUME_GOOGLE_CLIENT_ID=
REACTIVE_RESUME_GOOGLE_CLIENT_SECRET=
# ${REACTIVE_RESUME_PUBLIC_URL}/api/auth/google/callback
REACTIVE_RESUME_GOOGLE_CALLBACK_URL=
###< Reactive Resume ###
```

<p>
</details>

<details><summary><code>compose.yaml</code></summary>
<p>

```yaml
x-restart: &restart-stopped
  restart: unless-stopped

services:
  reactive-resume:
    image: amruthpillai/reactive-resume:${REACTIVE_RESUME_SERVER_IMAGE_VERSION:-latest}
    security_opt:
      - no-new-privileges:true
    restart: always
    depends_on:
      - postgres
      - chrome
    environment:
      TZ: ${REACTIVE_RESUME_TZ:-UTC}
      NODE_ENV: ${REACTIVE_RESUME_NODE_ENV:-production}
      PUBLIC_URL: ${REACTIVE_RESUME_PUBLIC_URL:-http://localhost:3000}
      DATABASE_URL: ${REACTIVE_RESUME_DATABASE_URL:?}
      ACCESS_TOKEN_SECRET: ${REACTIVE_RESUME_ACCESS_TOKEN_SECRET:?}
      REFRESH_TOKEN_SECRET: ${REACTIVE_RESUME_REFRESH_TOKEN_SECRET:?}
      CHROME_TOKEN: ${BROWSERLESS_CHROME_TOKEN:?}
      CHROME_URL: ${REACTIVE_RESUME_CHROME_URL:-ws://chrome:3000}
      MAIL_FROM: ${REACTIVE_RESUME_MAIL_FROM:-noreply@${APP_DOMAIN}}
      SMTP_URL: ${REACTIVE_RESUME_SMTP_URL:-smtp://null}
      STORAGE_URL: ${REACTIVE_RESUME_STORAGE_URL:-http://localhost:${REACTIVE_RESUME_STORAGE_PORT:-9000}/${STORAGE_BUCKET:-default}}
      STORAGE_ENDPOINT: ${REACTIVE_RESUME_STORAGE_ENDPOINT:-}
      STORAGE_PORT: ${REACTIVE_RESUME_STORAGE_PORT:-}
      STORAGE_REGION: ${REACTIVE_RESUME_STORAGE_REGION:-}
      STORAGE_BUCKET: ${REACTIVE_RESUME_STORAGE_BUCKET:-default}
      STORAGE_ACCESS_KEY: ${REACTIVE_RESUME_STORAGE_ACCESS_KEY:-}
      STORAGE_SECRET_KEY: ${REACTIVE_RESUME_STORAGE_SECRET_KEY:-}
      STORAGE_USE_SSL: ${REACTIVE_RESUME_STORAGE_USE_SSL:-false}
      SKIP_STORAGE_BUCKET_CHECK: ${REACTIVE_RESUME_SKIP_STORAGE_BUCKET_CHECK:-false}
      CROWDIN_PROJECT_ID: ${REACTIVE_RESUME_CROWDIN_PROJECT_ID:-}
      CROWDIN_PERSONAL_TOKEN: ${REACTIVE_RESUME_CROWDIN_PERSONAL_TOKEN:-}
      DISABLE_EMAIL_AUTH: ${REACTIVE_RESUME_DISABLE_EMAIL_AUTH:-true}
      VITE_DISABLE_SIGNUPS: ${REACTIVE_RESUME_VITE_DISABLE_SIGNUPS:-true}
      GITHUB_CLIENT_ID: ${REACTIVE_RESUME_GITHUB_CLIENT_ID:-}
      GITHUB_CLIENT_SECRET: ${REACTIVE_RESUME_GITHUB_CLIENT_SECRET:-}
      GITHUB_CALLBACK_URL: ${REACTIVE_RESUME_GITHUB_CALLBACK_URL:-http://localhost:5173/api/auth/github/callback}
      GOOGLE_CLIENT_ID: ${REACTIVE_RESUME_GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${REACTIVE_RESUME_GOOGLE_CLIENT_SECRET:-}
      GOOGLE_CALLBACK_URL: ${REACTIVE_RESUME_GOOGLE_CALLBACK_URL:-http://localhost:5173/api/auth/google/callback}
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.reactive-resume.tls: true
      traefik.http.routers.reactive-resume.entrypoints: websecure
      traefik.http.routers.reactive-resume.rule: Host(`resume.${APP_DOMAIN}`)
      traefik.http.routers.reactive-resume.service: reactive-resume
      traefik.http.services.reactive-resume.loadbalancer.server.port: 3000
      # Bypass `/artboard` route for chrome container to generate previews and PDFs (and builder in UI) in case you have auth middleware
      traefik.http.routers.reactive-resume-bypass.tls: true
      traefik.http.routers.reactive-resume-bypass.entrypoints: websecure
      traefik.http.routers.reactive-resume-bypass.rule: Host(`resume.${APP_DOMAIN}`) && PathPrefix(`/artboard`)
      traefik.http.routers.reactive-resume-bypass.service: reactive-resume-bypass
      traefik.http.services.reactive-resume-bypass.loadbalancer.server.port: 3000
    networks:
      - reactive-resume
      - proxy

  chrome:
    image: ghcr.io/browserless/chromium:${BROWSERLESS_CHROME_IMAGE_VERSION}
    <<: [*restart-stopped]
    environment:
      DEBUG: '*'
      TOKEN: ${BROWSERLESS_CHROME_TOKEN:?}
      EXIT_ON_HEALTH_FAILURE: ${BROWSERLESS_EXIT_ON_HEALTH_FAILURE:-true}
      HEALTH: ${BROWSERLESS_HEALTH:-true}
    networks:
      - reactive-resume

  postgres:
    image: postgres:${POSTGRES_IMAGE_VERSION}
    <<: [*restart-stopped]
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - reactive-resume

  wait:
    image: waisbrot/wait
    environment:
      TARGETS: postgres:5432 chrome:3000 reactive-resume:3000
      TIMEOUT: 60
    networks:
      - reactive-resume

volumes:
  postgres:
    driver: local

networks:
  reactive-resume:
    driver: bridge
  proxy:
    external: true
```

<p>
</details>

### What template are you using?

None
