### ISSUE TITLE
[Support request] How to run it using podman

### ISSUE THREAD

**Issue by guidot** [AmruthPillai/Reactive-Resume#1918]
Hi,
I love your project and I am trying to self host it using rootless podman instead of docker.

Using the below setup I get this error:
```
/app/dist/apps/server/main.js:554
throw new common_1.InternalServerErrorException(error);
      ^

InternalServerErrorException: write EPROTO 4028CBE2327F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:

at StorageService.onModuleInit (/app/dist/apps/server/main.js:554:19)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Promise.all (index 0)
at async callModuleInitHook (/app/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1__@nestjs+platform_k3xx66d35pcgv4we7xkfmupjtu/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:5)
at async NestApplication.callInitHook (/app/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1__@nestjs+platform_k3xx66d35pcgv4we7xkfmupjtu/node_modules/@nestjs/core/nest-application-context.js:223:13)
at async NestApplication.init (/app/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1__@nestjs+platform_k3xx66d35pcgv4we7xkfmupjtu/node_modules/@nestjs/core/nest-application.js:100:9)
at async NestApplication.listen (/app/node_modules/.pnpm/@nestjs+core@10.3.8_@nestjs+common@10.3.8_reflect-metadata@0.2.2_rxjs@7.8.1__@nestjs+platform_k3xx66d35pcgv4we7xkfmupjtu/node_modules/@nestjs/core/nest-application.js:169:33)
at async bootstrap (/app/dist/apps/server/main.js:14079:5) {
response: Error: write EPROTO 4028CBE2327F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:

at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16) {
errno: -71,
code: 'EPROTO',
syscall: 'write'
},
status: 500,
options: {}
}

Node.js v20.13.1
 ELIFECYCLE  Command failed with exit code 1.
```
This is the exact same error as [here](https://github.com/AmruthPillai/Reactive-Resume/issues/1561#issuecomment-1824023247) even though I set `STORAGE_USE_SSL: false`.

I am at a loss here. I'd be thankful for any hint on what could be causing this.

System:
```
Debian 12 (bookworm)
podman 4.3.1+ds1-8+b1
podman-compose 1.0.3-3
```

docker-compose.yml:
```
version: '3.8'

x-restart: &restart_stopped
  restart: unless-stopped

services:
  app:
    image: amruthpillai/reactive-resume:latest
    <<: *restart_stopped
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - minio
      - chrome
    environment:
      PORT: 3000
      NODE_ENV: production
      PUBLIC_URL: http://localhost:3000
      DATABASE_URL: postgresql://postgres:some_pg_password@postgres:5432/postgres
      ACCESS_TOKEN_SECRET: some_access_token
      REFRESH_TOKEN_SECRET: some_refresh_token
      CHROME_TOKEN: some_chrome_token
      CHROME_URL: ws://chrome:3000
      MAIL_FROM: Reactive Resume <name@example.com>
      SMTP_URL: smtp://name@example.com:some_smtp_password@example.com:587
      STORAGE_URL: http://localhost:9000/default
      STORAGE_ENDPOINT: minio
      STORAGE_PORT: 9000
      STORAGE_BUCKET: default
      STORAGE_ACCESS_KEY: minioadmin
      STORAGE_SECRET_KEY: some_minio_key
      STORAGE_USE_SSL: false
      DISABLE_EMAIL_AUTH: false
      VITE_DISABLE_SIGNUPS: true

  # Storage (for image uploads)
  minio:
    image: minio/minio
    <<: *restart_stopped
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: some_minio_key

  chrome:
    image: ghcr.io/browserless/chromium:latest
    <<: *restart_stopped
    environment:
      TIMEOUT: 10000
      CONCURRENT: 10
      TOKEN: some_chrome_token
      EXIT_ON_HEALTH_FAILURE: true
      PRE_REQUEST_HEALTH_CHECK: true

  postgres:
    image: postgres:16-alpine
    <<: *restart_stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: some_pg_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  minio_data:

```
