### ISSUE TITLE
[Bug] Profile image is still broken

### ISSUE THREAD

**Issue by kozmotronik** [AmruthPillai/Reactive-Resume#2209]
### Is there an existing issue for this?

- [x] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Self-Hosted

### Current Behavior

It does not display the uploaded profile image.

### Expected Behavior

It should display the uploaded profile image.

### Steps To Reproduce

1. Just upload an image to the integrated storage

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

None

### Anything else?

Hi!
I've updated my instance to the latest version to v4.4.4 with the hope of the broken images would be fixed as mentioned in [v4.4.4 relase notes](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v4.4.4). However it is still showing the profile images broken for all templates, I also tried it in Firefox. See below screenshots:
|||
|--|--|
|![Image](https://github.com/user-attachments/assets/c102e782-07d6-4c65-9787-96c291b20312)|![Image](https://github.com/user-attachments/assets/124df30a-f271-4d7f-a5d5-74aa4d0faab0)|

![Image](https://github.com/user-attachments/assets/e49d6c34-4cd4-48ac-9ffd-6fd381533d0e)

I don't know, maybe this could be a specific problem to my self-hosted installation. So I kindly request your help to detect what's wrong and fix it.

My instance is deployed using [Coolify](https://coolify.io) which is also self-hosted. When I have a look at the docker logs of the Reactive-Resume, I see the following lines when it is launched by Coolify:
```
2025-02-07T11:44:27.849897856Z [Nest] 84  - 02/07/2025, 11:44:27 AM     LOG ;5;3m[InstanceLoader] StorageModule dependencies initialized;5;3m +7ms
2025-02-07T11:44:27.850224076Z [Nest] 84  - 02/07/2025, 11:44:27 AM     LOG ;5;3m[InstanceLoader] HealthModule dependencies initialized;5;3m +1ms
2025-02-07T11:44:27.852585783Z [Nest] 84  - 02/07/2025, 11:44:27 AM     LOG ;5;3m[InstanceLoader] UserModule dependencies initialized;5;3m +2ms
2025-02-07T11:44:27.852765910Z [Nest] 84  - 02/07/2025, 11:44:27 AM     LOG ;5;3m[InstanceLoader] ResumeModule dependencies initialized;5;3m +0ms
2025-02-07T11:44:27.853015195Z [Nest] 84  - 02/07/2025, 11:44:27 AM     LOG ;5;3m[InstanceLoader] AuthModule dependencies initialized;5;3m +0ms
2025-02-07T11:44:27.861659706Z Warning: connect.session() MemoryStore is not
2025-02-07T11:44:27.861724797Z designed for a production environment, as it will leak
2025-02-07T11:44:27.861733547Z memory, and will not scale past a single process.
```

Also here is the docker-compose stack used by Coolify for the deployment, if it helps:
```yml
services:
  reactive-resume:
    image: 'amruthpillai/reactive-resume:latest'
    environment:
      - SERVICE_FQDN_REACTIVERESUME_3000
      - PUBLIC_URL=$SERVICE_FQDN_REACTIVERESUME
      - 'STORAGE_URL=${SERVICE_FQDN_MINIO}/default'
      - 'DATABASE_URL=postgresql://$SERVICE_USER_POSTGRES:$SERVICE_PASSWORD_POSTGRES@postgres:5432/${POSTGRES_DB:-postgres}'
      - ACCESS_TOKEN_SECRET=$SERVICE_PASSWORD_ACCESSTOKEN
      - REFRESH_TOKEN_SECRET=$SERVICE_PASSWORD_REFRESHTOKEN
      - CHROME_TOKEN=$SERVICE_PASSWORD_CHROMETOKEN
      - 'CHROME_URL=ws://chrome:3000/chrome'
      - 'REDIS_URL=redis://redis:6379'
      - STORAGE_ENDPOINT=minio
      - STORAGE_PORT=9000
      - STORAGE_REGION=us-east-1
      - STORAGE_BUCKET=default
      - STORAGE_ACCESS_KEY=$SERVICE_USER_MINIO
      - STORAGE_SECRET_KEY=$SERVICE_PASSWORD_MINIO
      - STORAGE_USE_SSL=false
      - 'DISABLE_SIGNUPS=${SERVICE_DISABLE_SIGNUPS:-false}'
      - 'DISABLE_EMAIL_AUTH=${SERVICE_DISABLE_EMAIL_AUTH:-false}'
    depends_on:
      - postgres
      - minio
      - chrome
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB:-postgres}'
      - POSTGRES_USER=$SERVICE_USER_POSTGRES
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10
  minio:
    image: 'quay.io/minio/minio:latest'
    command: 'server /data --console-address ":9001"'
    environment:
      - MINIO_SERVER_URL=$MINIO_SERVER_URL
      - MINIO_BROWSER_REDIRECT_URL=$MINIO_BROWSER_REDIRECT_URL
      - MINIO_ROOT_USER=$SERVICE_USER_MINIO
      - MINIO_ROOT_PASSWORD=$SERVICE_PASSWORD_MINIO
    volumes:
      - 'minio-data:/data'
    healthcheck:
      test:
        - CMD
        - mc
        - ready
        - local
      interval: 5s
      timeout: 20s
      retries: 10
  chrome:
    image: 'ghcr.io/browserless/chrome:latest'
    platform: linux/amd64
    environment:
      - HEALTH=true
      - TIMEOUT=10000
      - CONCURRENT=10
      - TOKEN=$SERVICE_PASSWORD_CHROMETOKEN
  redis:
    image: 'redis:7-alpine'
    command: redis-server
    volumes:
      - 'redis_data:/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 5s
      timeout: 20s
      retries: 10

```
