### ISSUE TITLE
[Feature] Add custom classes to sections for CSS customization

### ISSUE THREAD

**Issue by starbuck93** [AmruthPillai/Reactive-Resume#2223]
### Is there an existing issue for this feature?

- [x] Yes, I have searched the existing issues and it doesn't exist.

### Feature Description

Hey! I was searching for a way to "unbold" my Skills items with CSS, but it doesn't look like there are any classes I could assign that to without messing with other bold items. In my theme, it looks like everything uses the font-bold class, Additionally, I wanted to underline the "title" of each section, but that was straightforward since they're all H4s. 

```css
h4 {
  text-decoration: underline;
  text-decoration-thickness: 1px; /* Adjust thickness as needed */
  text-underline-offset: 2px; /* Adjust offset as needed */
}
```

Could there be a way to add a class to a section to then be able to apply whatever CSS to that section?

![Image](https://github.com/user-attachments/assets/c69604ac-ae1a-4114-8a03-a5b94dd506ae)

Or should this just be a custom theme I'm describing? Thanks!
