### ISSUE TITLE
Passing in env in Docker doesn't work

### ISSUE THREAD

**Issue by vladzaharia** [AmruthPillai/Reactive-Resume#436]
Howdy, I'm trying to set up v2 within my k8s cluster. I've created all the environment variables related to Firebase, but they don't seem to be picked up.

Env variables defined (I cut off the rest since there's secrets there):
<img width="409" alt="image" src="https://user-images.githubusercontent.com/79390/106398657-09dd3380-63c9-11eb-96c1-a90f6f233771.png">

But I'm still getting the same console errors:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/79390/106398690-3729e180-63c9-11eb-950d-06ec91fd17b7.png">

I do see in another issue (#416) that you haven't tested this way yet, just wondering if this is still the case?

For now, I'll likely switch to v1 so it can be run, but is there a supported way to upgrade from v1 to v2 down the line?

**Comment by mlow** [comment]
Like https://github.com/AmruthPillai/Reactive-Resume/issues/416#issuecomment-753572969 by @AmruthPillai mentioned, the variables must be present in the build environment of the image, making the image available on Dockerhub not useful. The suggestion to pass environment variables to a running container or to include a `.env` file from the builder stage in this case won't help - the variables are only read in the build stage.

My PR (#459) adjusts the Dockerfile to simplify the "baking-in" of the variables into the built image. I am using it will the following compose file, and it works:
```yml
version: "3.8"

services:
  reactive-resume:
    build:
      # note the context below is of my fork based on the develop branch - might want to wait until this is merged
      context: https://github.com/mlow/Reactive-Resume.git#develop
      args:
        FIREBASE_APIKEY: ""
        FIREBASE_APPID: ""
        FIREBASE_AUTHDOMAIN: ""
        FIREBASE_DATABASEURL: ""
        FIREBASE_MEASUREMENTID: ""
        FIREBASE_MESSAGINGSENDERID: ""
        FIREBASE_PROJECTID: ""
        FIREBASE_STORAGEBUCKET: ""
    ports:
      - '80:80'
```
