### ISSUE TITLE
When I visite the web page the content flashes then everything turns black. 

### ISSUE THREAD

**Issue by DistractedCanuck** [AmruthPillai/Reactive-Resume#493]
I'm trying to self host this on my ubuntu server via docker. I am running it with the following docker-compose.yml 

```
version: "2.1"
networks:
    Net:
        external: true
services:
    RxResume:
        image: amruthpillai/reactive-resume
        container_name: RxResume
        #volumes:
        ports:
            - 5050:80
        networks:
            Net:  
        restart: unless-stopped

```
I can navigate to the page in my browser.  The favicon appears and the content flashes for a moment then everything goes black.  

I'm honestly not sure what to do or what the issues it.  I'm using brave and it happens when using edge as well. 

Thanks for any help!
