### ISSUE TITLE
how should i use the docker image?

### ISSUE THREAD

**Issue by ChenchaoZhao** [AmruthPillai/Reactive-Resume#502]
what’s the entry point the docker image?
i don’t see service port exposed in dockerfile
how can i run the app from the docker image?

**Comment by C-Fu** [comment]
poor documentation. anyway I just did this
docker run -d -it --name rxresume -p 5151:80 amruthpillai/reactive-resume

although in my case when I open theip:5151 it appears then quickly disappears for some reason, unlike when I did it last year

**Comment by ChenchaoZhao** [comment]
thanks. that’s what i tired. i ran the image then it quit instantly.

**Comment by bolanoid** [comment]
> poor documentation. anyway I just did this
> docker run -d -it --name rxresume -p 5151:80 amruthpillai/reactive-resume
> 
> although in my case when I open theip:5151 it appears then quickly disappears for some reason, unlike when I did it last year

Same thing here, it appears and then quickly disappears.

**Comment by modem7** [comment]
> > poor documentation. anyway I just did this
> > docker run -d -it --name rxresume -p 5151:80 amruthpillai/reactive-resume
> > although in my case when I open theip:5151 it appears then quickly disappears for some reason, unlike when I did it last year
> 
> Same thing here, it appears and then quickly disappears.

#430 is related to this.

If you need a compose layout, this is mine, hope it helps once the Docker version gets fixed: 

```
  reactive-resume:
    image: amruthpillai/reactive-resume:latest
    container_name: ReactiveResume
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - FIREBASE_APIKEY=$FIREBASE_APIKEY
      - FIREBASE_APPID=$FIREBASE_APPID
      - FIREBASE_AUTHDOMAIN=$FIREBASE_AUTHDOMAIN
      - FIREBASE_DATABASEURL=$FIREBASE_DATABASEURL
      - FIREBASE_MEASUREMENTID=$FIREBASE_MEASUREMENTID
      - FIREBASE_MESSAGINGSENDERID=$FIREBASE_MESSAGINGSENDERID
      - FIREBASE_PROJECTID=$FIREBASE_PROJECTID
      - FIREBASE_STORAGEBUCKET=$FIREBASE_STORAGEBUCKET
    networks: #Prevents Docker from creating a default stack network
      pihole:
        ipv4_address: '172.22.0.124'
    ports:
      - 7654:80
    labels:
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.resume-rtr.entrypoints=https"
      - "traefik.http.routers.resume-rtr.rule=Host(`resume.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.resume-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.http.routers.resume-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      # - "traefik.http.routers.resume-rtr.middlewares=chain-oauth@file" # Google OAuth 2.0
      #- "traefik.http.routers.resume-rtr.middlewares=chain-authelia@file" # Authelia
      ## HTTP Services
      - "traefik.http.routers.resume-rtr.service=resume-svc"
      - "traefik.http.services.resume-svc.loadbalancer.server.port=80"
      # Healthcheck
      - "traefik.http.services.resume-svc.loadbalancer.healthcheck.interval=10s"
      - "traefik.http.services.resume-svc.loadbalancer.healthcheck.timeout=5s"
      - "traefik.http.services.resume-svc.loadbalancer.healthcheck.path=/"
```
