### ISSUE TITLE
For the one looking for help

### ISSUE THREAD

**Issue by martadinata666** [AmruthPillai/Reactive-Resume#574]
I created the dev image at [reactive-resume](https://hub.docker.com/repository/docker/martadinata666/reactive-resume) and here few help to do it.

# Reactive Resume
![rx-img](https://res.cloudinary.com/dedyms/image/upload/c_thumb,w_200,g_face/v1634791122/container/logo_ms6idb.png)

[![pipeline status](https://gitlab.com/dedyms/reactive-resume/badges/master/pipeline.svg)](https://gitlab.com/dedyms/reactive-resume/-/commits/master)

* ### https://github.com/AmruthPillai/Reactive-Resume (source)
* ### https://github.com/martadinata666/Reactive-Resume (Forked)
* ### https://registry.gitlab.com/dedyms/reactive-resume

## Supported tags
*  [develop](https://gitlab.com/dedyms/reactive-resume/-/blob/master/Dockerfile)

## Usage
```
docker run -d -p <desired port>:8000 -v ./env:/home/node/reactive-resume/.env martadinata666/reactive-resume:<tag>
```

## Compose
```
version: "3.5"
services:
  app:
    image: martadinata666/reactive-resume:develop
    volumes:
      - ./env-file:/home/node/reactive-resume/.env
    ports:
      - <desired ports>:8000
```
After start up need to wait to a minute or more depends on your machine, wait application logs say web ready at `http://localhost:8000 etc`

![logs](https://res.cloudinary.com/dedyms/image/upload/v1634792353/container/logs_m8z1cx.png)

## env sample
```
FIREBASE_APIKEY=""
FIREBASE_APPID=""
FIREBASE_AUTHDOMAIN=""
FIREBASE_DATABASEURL=""
FIREBASE_MEASUREMENTID="" 
FIREBASE_MESSAGINGSENDERID=""
FIREBASE_PROJECTID=""
FIREBASE_STORAGEBUCKET=""
#GATSBY_CPU_COUNT=2

```

### Getting code from firebase
* #### https://github.com/AmruthPillai/Reactive-Resume/blob/develop/DEPLOYMENT.md

`FIREBASE_MEASUREMENTID` could be empty.

## Authentication
Authentication separated by two segments, how it authenticate and from where it authenticate.

Taken from https://github.com/firebase/firebase-js-sdk/issues/3188#issuecomment-715264122

* Before using apps need to enable authentication method by firebase. 
1. Go to Firebase console
2. Goto Authentication
3. Add Google as authentication method.

* Add `Authorized Domains`
1. Simply enter your host IP address, assuming Reactive Resume app at `192.168.0.2` then enter the domain as `192.168.0.2`

#### How it look like after auth setup
![auth](https://res.cloudinary.com/dedyms/image/upload/c_scale,w_776/v1634804525/container/auth_z3pusb.png)

## Extracting static files
To serve static files web using nginx, 
1. Exec into container, `docker exec -it -u 1000 container_name bash`, then run `npm run build`
2. Copy out `/home/node/reactive-resume/public` to local. `docker cp container_name:/home/node/reactive-resume/public ./`

## Serving static files
1. Create nginx.conf
```
server {
        listen 80 http2;

        root /var/www/html/;

        # Add index.php to the list if you are using PHP
        index index.html;

        server_name _;
}
```
2. Create compose file nginx with custom conf
```
version: "3.5"
services:
  static:
    image: martadinata666/nginx:mainline
    volumes:
      - ./public:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - <desired_port>:80
```

**Comment by trailingslash** [comment]
Didn't have success with this one - Portainer froze and I had to manually remove the container.

**Comment by martadinata666** [comment]
yah this pretty much outdated, after updated few things.
```
version: "3.5"
services:
  web:
    image: martadinata666/reactive-resume:develop
    ports:
      - 7000:8000
    volumes:
      - ./env:/home/debian/reactive-resume/.env
    networks:
      - reactive-resume

networks:
  reactive-resume:
    name: reactive-resume%   
```
