### ISSUE TITLE
[BUG] Login with Google unresponsive

### ISSUE THREAD

**Issue by modem7** [AmruthPillai/Reactive-Resume#691]
**Describe the bug**
When attempting to login with Google, the button clicks, but otherwise is non-responsive. 

**To Reproduce**
![image](https://user-images.githubusercontent.com/4349962/158247682-c3913656-cbd8-467f-9243-4f71daa2379e.png)

**Google Settings**
Authorised JavaScript origins:
https://resume.mydomain.com

Authorised redirect URIs:
https://resume.mydomain.com/api/v2/auth/oauth2/google/callback

**Docker Compose**
```yaml
  reactiveresumeserver:
    image: amruthpillai/reactive-resume:server-latest
    container_name: ReactiveResume-Server
    environment:
      - PUBLIC_URL=https://resume.$DOMAINNAME
      - POSTGRES_HOST=reactiveresumedb
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USERNAME=postgres
      - TZ=$TZ
      - SECRET_KEY=mypassword
      - JWT_SECRET=mypassword
      - JWT_EXPIRY_TIME=604800
    depends_on:
      - reactiveresumedb
    networks:
      pihole:
        ipv4_address: '172.22.0.140'
      isolated:
    labels: 
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.resumeserver-rtr.entrypoints=https"
      - "traefik.http.routers.resumeserver.rule=Host(`resume.$DOMAINNAME`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.resumeserver.middlewares=server-stripprefix"
      - "traefik.http.routers.resumeserver-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.resumeserver-rtr.middlewares=chain-no-auth@file" # No Authentication
      - "traefik.http.middlewares.resumeserver-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.resumeserver-stripprefix.stripprefix.forceslash=true"
      ## HTTP Services
      - "traefik.http.routers.resumeserver-rtr.service=resumeserver-svc"
      - "traefik.http.services.resumeserver-svc.loadbalancer.server.port=3100"      

  reactiveresumeclient:
    image: amruthpillai/reactive-resume:client-latest
    container_name: ReactiveResume-Client
    environment:
      - PUBLIC_SERVER_URL=https://resume.$DOMAINNAME/api
      - TZ=$TZ
      - SECRET_KEY=mypassword
      - JWT_SECRET=mypassword
      - JWT_EXPIRY_TIME=604800
      - PUBLIC_GOOGLE_CLIENT_ID=googleID
      - GOOGLE_CLIENT_SECRET=googlesecret
      - GOOGLE_API_KEY=myapikey
    depends_on:
      - reactiveresumeserver
    networks:
      pihole:
        ipv4_address: '172.22.0.141'
    labels: 
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.resume-rtr.entrypoints=https"
      - "traefik.http.routers.resume-rtr.rule=Host(`resume.$DOMAINNAME`)"
      - "traefik.http.routers.resume-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.resume-rtr.middlewares=chain-no-auth@file" # No Authentication
      ## HTTP Services
      - "traefik.http.routers.resume-rtr.service=resume-svc"
      - "traefik.http.services.resume-svc.loadbalancer.server.port=3000"
      ## Flame Dashboard
      - flame.type=application # "app" works too
      - flame.name=ReactiveResume
      - flame.icon=https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/HeimdallIcons/resume.png
      # - flame.icon=custom to make changes in app. ie: custom icon upload

  reactiveresumedb:
    image: postgres:alpine
    container_name: ReactiveResume-DB
    environment:
      - TZ=$TZ
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=postgres
    networks:
      - isolated
    ports:
      - 5432:5432
    volumes:
      - $USERDIR/ReactiveResume:/var/lib/postgresql/data
```
