### ISSUE TITLE
[BUG] 404 Page Not Found

### ISSUE THREAD

**Issue by AzamServer** [AmruthPillai/Reactive-Resume#708]
**Describe the bug**
Getting a "404 page not found" error when trying to access the webpage

**To Reproduce**
1. Copy my docker-compose.yml file
2. Copy my .env file
3. Compile and run the docker
4. Access the webpage

**Expected behavior**
I expect to be able to access the application.

**Screenshots**
![Screen Shot 2022-03-15 at 8 48 35 PM](https://user-images.githubusercontent.com/78570129/158495388-c85834a2-1c5d-4bcf-a041-8d3ddeb73b53.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 15.4

**Additional context**
My docker-compose.yml file:
```yml
version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: reactive-resume-postgres
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - ./config:/var/lib/postgresql/data

  traefik:
    image: traefik:latest
    container_name: reactive-resume-traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 8281:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  server:
    image: amruthpillai/reactive-resume:server-latest
    container_name: reactive-resume-server
    env_file: .env
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - traefik
      - postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.server.entrypoints=web
      - traefik.http.routers.server.rule=Host(`<SERVER-IP>`) && PathPrefix(`/api/`)
      - traefik.http.routers.server.middlewares=server-stripprefix
      - traefik.http.middlewares.server-stripprefix.stripprefix.prefixes=/api
      - traefik.http.middlewares.server-stripprefix.stripprefix.forceslash=true

  client:
    image: amruthpillai/reactive-resume:client-latest
    container_name: reactive-resume-client
    env_file: .env
    depends_on:
      - traefik
      - server
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`<SERVER-IP>`)
      - traefik.http.routers.client.entrypoints=web
```

My .env file:
```shell
# App
TZ=America/New_York
SECRET_KEY=<hidden>

# URLs
PUBLIC_URL=http://192.168.1.78:8281/
PUBLIC_SERVER_URL=http://192.168.1.78:8281/api

# Database
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_USERNAME=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DATABASE=postgres
POSTGRES_SSL_CERT=

# Auth
JWT_SECRET=<hidden>
JWT_EXPIRY_TIME=604800

# Google
PUBLIC_GOOGLE_CLIENT_ID=change-me
GOOGLE_CLIENT_SECRET=change-me
GOOGLE_API_KEY=change-me

# SendGrid (Optional)
SENDGRID_API_KEY=
SENDGRID_FORGOT_PASSWORD_TEMPLATE_ID=
SENDGRID_FROM_NAME=
SENDGRID_FROM_EMAIL=
```

**Comment by modem7** [comment]
Make sure to update the <SERVER-IP> parts

**Comment by AzamServer** [comment]
This is my new docker-compose.yml, and I am still getting the same error:

```yml
version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: reactive-resume-postgres
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - ./config:/var/lib/postgresql/data

  traefik:
    image: traefik:latest
    container_name: reactive-resume-traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 8281:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  server:
    image: amruthpillai/reactive-resume:server-latest
    container_name: reactive-resume-server
    env_file: .env
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - traefik
      - postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.server.entrypoints=web
      - traefik.http.routers.server.rule=Host(`192.168.1.78:8281`) && PathPrefix(`/api/`)
      - traefik.http.routers.server.middlewares=server-stripprefix
      - traefik.http.middlewares.server-stripprefix.stripprefix.prefixes=/api
      - traefik.http.middlewares.server-stripprefix.stripprefix.forceslash=true

  client:
    image: amruthpillai/reactive-resume:client-latest
    container_name: reactive-resume-client
    env_file: .env
    depends_on:
      - traefik
      - server
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`192.168.1.78:8281`)
      - traefik.http.routers.client.entrypoints=web
```

**Comment by didikrm** [comment]
Try to remove the port number from the IP address i.e. 192.168.1.78:8281 -> 192.168.1.78

**Comment by vitobotta** [comment]
Actually re-reading I realized my problem is different because I can access the web interface. Sorry - will open another issue.

**Comment by AzamServer** [comment]
I started to get the same error. What am I doing wrong?
```yml
version: '3'

x-env-shared: &env-shared
  environment:
    - TZ=America/New_York
    - PUBLIC_URL=https://reactiveresume.azamserver.com/
    - PUBLIC_SERVER_URL=http://reactiveresume.azamserver.com/api

x-env-server: &env-server
  environment:
    - SECRET_KEY=qfPK3zfQWWd9akcDboy505a9EcAhSjOrrEu53Sx2mwlZAJdi0iE4v82IEZAYhOY2xvNQIbFRuQiWD1XZ4rU3yYwJEPGMHMkRclfBccTemRIHCBSxQAELzBeKWbA4fAKD
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DATABASE=postgres
    - JWT_SECRET=qqGN9xdwG3xwBBiHQMIA5SqhB9Kz4WNmZy2l2Xp5dtqGRcPk5GkWDJA97nphdqcwr2W5bUuSs6jFBWcmX6FOPyNPZPODCfVSrvsJSFvkJCt1ThDxnDvq11yed7LERxmJ
    - JWT_EXPIRY_TIME=604800

x-env-flags: &env-flags
  environment:
    - PUBLIC_FLAG_DISABLE_SIGNUPS=true

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: reactive-resume-postgres
    volumes:
      - ./config:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      start_period: 15s
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always

  traefik:
    image: traefik:rocamadour
    container_name: reactive-resume-traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 8281:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  server:
    image: amruthpillai/reactive-resume:server-latest
    container_name: reactive-resume-server
    <<: *env-shared
    <<: *env-server
    depends_on:
      - traefik
      - postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.server.entrypoints=web
      - traefik.http.routers.server.rule=Host(`reactiveresume.azamserver.com`) && PathPrefix(`/api/`)
      - traefik.http.routers.server.middlewares=server-stripprefix
      - traefik.http.middlewares.server-stripprefix.stripprefix.prefixes=/api
      - traefik.http.middlewares.server-stripprefix.stripprefix.forceslash=true
    restart: always

  client:
    image: amruthpillai/reactive-resume:client-latest
    container_name: reactive-resume-client
    <<: *env-shared
    <<: *env-flags
    depends_on:
      - traefik
      - server
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`reactiveresume.azamserver.com`)
      - traefik.http.routers.client.entrypoints=web
    restart: always
```

**Comment by AzamServer** [comment]
This docker-compose.yml file is giving me the same error. What am I doing wrong?
```yml
version: '3'

x-env-shared: &env-shared
  environment:
    - TZ=America/New_York
    - PUBLIC_URL=https://<URL REMOVED>/
    - PUBLIC_SERVER_URL=https://<URL REMOVED>/api

x-env-server: &env-server
  environment:
    - SECRET_KEY=qfPK3zfQWWd9akcDboy505a9EcAhSjOrrEu53Sx2mwlZAJdi0iE4v82IEZAYhOY2xvNQIbFRuQiWD1XZ4rU3yYwJEPGMHMkRclfBccTemRIHCBSxQAELzBeKWbA4fAKD
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DATABASE=postgres
    - JWT_SECRET=qqGN9xdwG3xwBBiHQMIA5SqhB9Kz4WNmZy2l2Xp5dtqGRcPk5GkWDJA97nphdqcwr2W5bUuSs6jFBWcmX6FOPyNPZPODCfVSrvsJSFvkJCt1ThDxnDvq11yed7LERxmJ
    - JWT_EXPIRY_TIME=604800

x-env-flags: &env-flags
  environment:
    - PUBLIC_FLAG_DISABLE_SIGNUPS=true

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: reactive-resume-postgres
    volumes:
      - ./config:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      start_period: 15s
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always

  traefik:
    image: traefik:rocamadour
    container_name: reactive-resume-traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 8281:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  server:
    image: amruthpillai/reactive-resume:server-latest
    container_name: reactive-resume-server
    <<: *env-shared
    <<: *env-server
    depends_on:
      - traefik
      - postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.server.entrypoints=web
      - traefik.http.routers.server.rule=Host(`<URL REMOVED>`) && PathPrefix(`/api/`)
      - traefik.http.routers.server.middlewares=server-stripprefix
      - traefik.http.middlewares.server-stripprefix.stripprefix.prefixes=/api
      - traefik.http.middlewares.server-stripprefix.stripprefix.forceslash=true
    restart: always

  client:
    image: amruthpillai/reactive-resume:client-latest
    container_name: reactive-resume-client
    <<: *env-shared
    <<: *env-flags
    depends_on:
      - traefik
      - server
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`<URL REMOVED>`)
      - traefik.http.routers.client.entrypoints=web
    restart: always
```
