### ISSUE TITLE
[FEATURE] CSS documentation 

### ISSUE THREAD

**Issue by Markg546** [AmruthPillai/Reactive-Resume#749]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can not edit the CSS of my resume because I do not know what to address to.

**Describe the solution you'd like**
A documentation of all names of elements used.

**Comment by 33masterman33** [comment]
All the elements (ids, classes, etc) can be found by using inspect element in your web browser. From there its just standard CSS coding using the id and class for whatever element you want to edit.

**Comment by kwuite** [comment]
@Markg546 

You can use the variables, but it won't be consistent and it will not cover dynamically css set by logic like the react-transform-wrapper. I propose to use my second more controlled option. 

```css
* {
    --text-color: red;
    --background-color: blue;
    --primary-color: green;
    --tw-border-spacing-x: 0;
    --tw-border-spacing-y: 0;
    --tw-translate-x: 0;
    --tw-translate-y: 0;
    --tw-rotate: 0;
    --tw-skew-x: 0;
    --tw-skew-y: 0;
    --tw-scale-x: 1;
    --tw-scale-y: 1;
    --tw-pan-x: ;
    --tw-pan-y: ;
    --tw-pinch-zoom: ;
    --tw-scroll-snap-strictness: proximity;
    --tw-ordinal: ;
    --tw-slashed-zero: ;
    --tw-numeric-figure: ;
    --tw-numeric-spacing: ;
    --tw-numeric-fraction: ;
    --tw-ring-inset: ;
    --tw-ring-offset-width: 0px;
    --tw-ring-offset-color: #fff;
    --tw-ring-color: rgba(59,130,246,.5);
    --tw-ring-offset-shadow: 0 0 #0000;
    --tw-ring-shadow: 0 0 #0000;
    --tw-shadow: 0 0 #0000;
    --tw-shadow-colored: 0 0 #0000;
    --tw-blur: ;
    --tw-brightness: ;
    --tw-contrast: ;
    --tw-grayscale: ;
    --tw-hue-rotate: ;
    --tw-invert: ;
    --tw-saturate: ;
    --tw-sepia: ;
    --tw-drop-shadow: ;
    --tw-backdrop-blur: ;
    --tw-backdrop-brightness: ;
    --tw-backdrop-contrast: ;
    --tw-backdrop-grayscale: ;
    --tw-backdrop-hue-rotate: ;
    --tw-backdrop-invert: ;
    --tw-backdrop-opacity: ;
    --tw-backdrop-saturate: ;
    --tw-backdrop-sepia: ;
    /* Dark body*/
    --tw-bg-opacity: 1;
    --tw-text-opacity: 1;
}
```

@33masterman33 it is not just standard CSS because there is logic involved in setting the border and background colors for rating the level of a skill. When CSS variables are being used we can just change the variable and be done with it. But some templates do not use variables and thus changing them will not affect the dynamically set colors. Changing the background of skills will just give you the full 5* or 100% which is of course not what we want. I checked the elements for a difference in set and unset classes to identify the rating of skills but there was no difference so I have no fix for those.

The best I came up with so far is the below (yes garbage) css code that gave me as much color control as possible.

```css
/* Fallback logic (Keep this on top) */
* {
    --text-color: red;
    --background-color: blue;
    --primary-color: green;
}

/* Titles / dates */
[class^='font-'] {
    color: green !important;
}
h1, h2, h3, h4 {
	color: green !important;
}
[class^='mt-'] {
	color: blue;
}

[class^='opacity-'] {
	color: blue;
}

/* Secondary titles */
div > span {
    color: yellow !important;
}

/* Links */
a{
    color: blue;
}

/* Intro / references */

.markdown p {
 color: #ffa700;
}

/* Project & work bullet points */
.markdown ul li {
	color: cyan;
}

/* Skills / bubbles */
ul > li > span {
	color: #ffa700 !important;
}

.grid > ul > li {
	background-color: white !important;
}

div.grid > div > div[class*='rounded-']{
	--primary-color: blue !important;
}

/* Markdown */

strong {
	color: blue;
}

/* Sidebar background */

[class*='_sidebar_'] {
	background-color: black !important;
}

/* Main page background */

[class*='_page_'], [class*='_main_'] {
	background-color: black !important;
}

/* Dots, Icons, all leftovers */
[class^='MuiSvgIcon'] {
	color: blue;
}

mr-2 h-3 w-3 rounded-full border {
	color: blue;
}

.rounded-sm.border-2 {
	color: blue;
	background-color: blue !important;
    border-color: blue !important;
}
```

As seen in the screenshot I was unable to change the skill level set by react-transform.
![image](https://user-images.githubusercontent.com/6716689/211112951-7fecf491-c8e1-42d4-862c-ba8f7c11f9e4.png)
