### ISSUE TITLE
[BUG] [Portainer specific] Environment variables are missing even if they've been entered

### ISSUE THREAD

**Issue by Pheggas** [AmruthPillai/Reactive-Resume#825]
**Describe the bug**
I entered all the required fields in both - docker-compose.yml and .env file

**Product Flavor**
- [ ] Managed (https://rxresu.me)
- [x] Self Hosted

**To Reproduce**

1. Deploy it as is described in https://docs.rxresu.me/deployment/docker

**Expected behavior**
Running smoothly without 'server' container bootloops

**Screenshots**
![image](https://user-images.githubusercontent.com/9994511/162566502-fb53a0f9-9179-4702-b4fd-8f6836be8ef9.png)
![image](https://user-images.githubusercontent.com/9994511/162566683-ba29f1aa-e504-4752-8286-abbab7c18cbc.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS (GNU/Linux 5.13.0-37-generic x86_64)
 - Browser: any
 - Version: 3.3.3

**Additional context**
The 'Server' container bootloops the whole time with same logs (see Screenshots section)

docker-compose.yml:

```
version:'3'

x-env-shared: &env-shared
  environment:
    - TZ=UTC
    - PUBLIC_URL=http://192.168.1.12
    - PUBLIC_SERVER_URL=http://192.168.1.12/api
    - PUBLIC_GOOGLE_CLIENT_ID=

x-env-database: &env-database
  environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres

x-env-server: &env-server
  environment:
    - SECRET_KEY=DvCIXtWHbXhD9blw1jJW
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - POSTGRES_SSL_CERT=
    - JWT_SECRET=DvCIXtWHbXhD9blw1jJW
    - JWT_EXPIRY_TIME=604800
    - PUBLIC_GOOGLE_CLIENT_ID=
    - GOOGLE_CLIENT_SECRET=
    - GOOGLE_API_KEY=removed_due_to_security_reasons
    - SENDGRID_API_KEY=
    - SENDGRID_FORGOT_PASSWORD_TEMPLATE_ID=
    - SENDGRID_FROM_NAME=
    - SENDGRID_FROM_EMAIL=
    - STORAGE_BUCKET=
    - STORAGE_REGION=
    - STORAGE_ENDPOINT=
    - STORAGE_URL_PREFIX=
    - STORAGE_ACCESS_KEY=
    - STORAGE_SECRET_KEY=

x-env-flags: &env-flags
  environment:
    - PUBLIC_FLAG_DISABLE_SIGNUPS=false

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: postgres
    <<: [*env-database]
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      start_period: 15s
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always

  traefik:
    image: traefik:rocamadour
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:3070
    ports:
      - 3070:3070
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  server:
    image: amruthpillai/reactive-resume:server-latest
    container_name: server
    <<: [*env-shared, *env-server, *env-database]
    depends_on:
      - traefik
      - postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.server.entrypoints=web
      - traefik.http.routers.server.rule=Host(`localhost`) && PathPrefix(`/api/`)
      - traefik.http.routers.server.middlewares=server-stripprefix
      - traefik.http.middlewares.server-stripprefix.stripprefix.prefixes=/api
      - traefik.http.middlewares.server-stripprefix.stripprefix.forceslash=true
    restart: always

  client:
    image: amruthpillai/reactive-resume:client-latest
    container_name: client
    <<: [*env-shared, *env-flags]
    depends_on:
      - traefik
      - server
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`192.168.1.12`)
      - traefik.http.routers.client.entrypoints=web
    restart: always

volumes:
  pgdata:
```
