### ISSUE TITLE
[BUG] AWS S3 client throwing error for MinIO S3 server

### ISSUE THREAD

**Issue by klejejs** [AmruthPillai/Reactive-Resume#829]
**Describe the bug**

I have locally setup MinIO S3 server, but when I set environment variables to connect to it, server throws an error `Error: self signed certificate`

**Product Flavor**
- [ ] Managed (https://rxresu.me)
- [x] Self Hosted

**To Reproduce**

1. Setup MinIO server and point environment variables to it
2. Go to 'resume builder'
3. Click on 'upload an image'
4. See error in server logs

**Expected behavior**

Image is uploaded

**Screenshots**

![image](https://user-images.githubusercontent.com/24546950/162615513-768b3ac1-2933-49c5-b140-f9ff58cef244.png)

**Desktop (please complete the following information):**
Irrelevant

**Additional context**

**Comment by AmruthPillai** [comment]
Do you require an SSL certificate to be passed when connecting to your S3 server?

**Comment by klejejs** [comment]
No, I don't. I can use AWS CLI without one and it is working fine.

**Comment by martadinata666** [comment]
Joining on this, how you setup the env? I got 403 that seems something denied but i dont know where. I tested with `awscli` by using https://docs.min.io/docs/aws-cli-with-minio.html , create bucket, add file, delete, etc fine.

My env with minio
```
# S3 Compliant storage
STORAGE_BUCKET=resume
STORAGE_REGION=us-east-1
STORAGE_ENDPOINT=http://192.168.0.2:9000
STORAGE_URL_PREFIX=rxrs
STORAGE_ACCESS_KEY=myaccesskey
STORAGE_SECRET_KEY=mysecretkey
```

**Comment by martadinata666** [comment]
> @martadinata666 Not a specialist on MinIO as I installed it just yesterday. The things I see that differ for us are:
> 
>     * in my setup `STORAGE_BUCKET` and `STORAGE_URL_PREFIX` were the same values though I am don't think that should matter
> 
>     * I immediately noticed that MinIO has an option to set storage region, so I changed it to a random string, but if it worked for you with `awscli`, I think this shouldn't be the problem either
> 
>     * I use my public URL as a storage endpoint because MinIO requires URL rewrites and I did not have it set up for local IP addresses, only public URL. Maybe this is the issue for you?

Me too, on deploy i use the simplest one here https://docs.min.io/docs/minio-docker-quickstart-guide.html , add secret and access key, the play around with `aws-cli` and `s3cmd` to confirm working, result 403 on my side.

**Comment by blumberg** [comment]
I'm having the same issue. I would like to build a fully self-hosted version, so I've opted for MinIO as there is no other local storage option at the moment.
I've deployed MinIO within a composer without any REGION set and created a bucket manually. MinIO is working fine with `aws` within the same compose (I've included an **awscli** docker to test it out with the same address). I could list files, remove files...
When moved to ReactiveResume app, it throw 403 error (see below)

```
[Nest] 42  - 05/02/2022, 5:08:23 PM   ERROR [ExceptionsHandler] Request failed with status code 403
Error: Request failed with status code 403
    at createError (/app/node_modules/.pnpm/axios@0.26.0/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/.pnpm/axios@0.26.0/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@0.26.0/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[Nest] 42  - 05/02/2022, 5:08:24 PM   ERROR [ExceptionsHandler] Request failed with status code 403
Error: Request failed with status code 403
    at createError (/app/node_modules/.pnpm/axios@0.26.0/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/.pnpm/axios@0.26.0/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@0.26.0/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[Nest] 42  - 05/02/2022, 5:08:25 PM   ERROR [ExceptionsHandler] Request failed with status code 403
Error: Request failed with status code 403
    at createError (/app/node_modules/.pnpm/axios@0.26.0/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/.pnpm/axios@0.26.0/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@0.26.0/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[Nest] 42  - 05/02/2022, 5:08:26 PM   ERROR [ExceptionsHandler] Request failed with status code 403
Error: Request failed with status code 403
    at createError (/app/node_modules/.pnpm/axios@0.26.0/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/.pnpm/axios@0.26.0/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@0.26.0/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[Nest] 42  - 05/02/2022, 5:08:28 PM   ERROR [ExceptionsHandler] getaddrinfo ENOTFOUND rxrs.storage
Error: getaddrinfo ENOTFOUND rxrs.storage
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
[Nest] 42  - 05/02/2022, 5:08:28 PM   ERROR [ExceptionsHandler] Request failed with status code 403
Error: Request failed with status code 403
    at createError (/app/node_modules/.pnpm/axios@0.26.0/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/.pnpm/axios@0.26.0/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@0.26.0/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

This is the Compose file i'm using:

```yaml
version: '3'

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: rxresume-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    volumes:
      - /portainer/Files/AppData/Config/ReactiveResume/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      start_period: 15s
      interval: 30s
      timeout: 30s
      retries: 3
    restart: unless-stopped
    networks:
      - reactiveresume

  storage:
    image: minio/minio:latest
    container_name: rxresume-storage
    expose:
      - 9000
      - 9090 # This port is to access the Web Interface
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - /portainer/Files/AppData/Config/ReactiveResume/data:/data
    restart: unless-stopped
    command: server --console-address ":9090" /data
    networks:
      - reactiveresume

  server:
    image: amruthpillai/reactive-resume:server-v3.3.4
    container_name: rxresume-server
    ports:
      - 7769:3100
    environment:
      - TZ=${TZ}
      - PUBLIC_URL=${PUBLIC_URL}
      - PUBLIC_SERVER_URL=${PUBLIC_SERVER_URL}
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_SSL_CERT=
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY_TIME=604800
      - GOOGLE_CLIENT_SECRET=
      - GOOGLE_API_KEY=
      - SENDGRID_API_KEY=
      - SENDGRID_FORGOT_PASSWORD_TEMPLATE_ID=
      - SENDGRID_FROM_NAME=
      - SENDGRID_FROM_EMAIL=
      - STORAGE_BUCKET=rxrs
      - STORAGE_REGION=myregion
      - STORAGE_ENDPOINT=http://storage:9000
      - STORAGE_URL_PREFIX=rxrs
      - STORAGE_ACCESS_KEY=ROOTUSER
      - STORAGE_SECRET_KEY=${MINIO_ROOT_PASSWORD}
    depends_on:
      - postgres
      - storage
    restart: unless-stopped
    networks:
      - reactiveresume

  client:
    image: amruthpillai/reactive-resume:client-v3.3.4
    container_name: rxresume-client
    ports:
      - 7768:3000
    environment:
      - TZ=${TZ}
      - PUBLIC_URL=${PUBLIC_URL}
      - PUBLIC_SERVER_URL=${PUBLIC_SERVER_URL}
      - PUBLIC_GOOGLE_CLIENT_ID=
      - PUBLIC_FLAG_DISABLE_SIGNUPS=${SIGNUP}
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - reactiveresume

  awscli:
    image: amazon/aws-cli:latest
    entrypoint: /bin/bash
    tty: yes
    restart: unless-stopped
    networks:
      - reactiveresume
  

networks:
  reactiveresume:
```

I don't know what is missing to get it working with MinIO.
