### ISSUE TITLE
[BUG] Print to PDF - ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by TheGreatSage** [AmruthPillai/Reactive-Resume#880]
**Describe the bug**

**Product Flavor**
- [ ] Managed (https://rxresu.me)
- [X] Self Hosted

**To Reproduce**

1. Host on docker behind traefik
2. Click on print to pdf
3. Get status 500 error.
4. Checking logs:
```
[Nest] 44  - 05/10/2022, 4:28:24 PM   ERROR [ExceptionsHandler] page.goto: net::ERR_NAME_NOT_RESOLVED at https://resume.com//username/resume/printer?secretKey=secret

=========================== logs ===========================
navigating to "https://resume.com//username/resume/printer?secretKey=secret", waiting until "load"
============================================================
    at PrinterService.printAsPdf (/app/server/dist/printer/printer.service.js:39:20)
```

**Expected behavior**
It should print to pdf but there seems to be something wrong with the routing I don't know about.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser All
 - Version 3.4.4

**Additional context**
Everything else seems to work fine, don't see any other errors being thrown in the server.
There is a similar issue opened about print to pdf not working but they are getting a different error.

**Docker compose**
```
version: '3'
services:
  resume-server:
    image: amruthpillai/reactive-resume:server-latest
    container_name: resume-server
    environment:
      - TZ=UTC
      - PUBLIC_URL=https://resume.com/
      - PUBLIC_SERVER_URL=https://resume.com/api
      - SECRET_KEY=<secret>
      - POSTGRES_HOST=<db>
      - POSTGRES_PORT=5432
      - POSTGRES_USER=resume
      - POSTGRES_PASSWORD=<pass>
      - POSTGRES_DB=resume
      - JWT_SECRET=<secret>
      - JWT_EXPIRY_TIME=604800
      - GOOGLE_API_KEY=<api>
    networks:
      - lab
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.resume-server.entrypoints=https
      - traefik.http.routers.resume-server.rule=Host(`resume.com`) && PathPrefix(`/api`)
      - traefik.http.routers.resume-server.service=resume-server
      - traefik.http.services.resume-server.loadbalancer.server.port=3100
      - traefik.http.routers.resume-server.tls.certresolver=letsEncrypt
      - traefik.http.routers.resume-server.middlewares=resume-stripprefix
      - traefik.http.middlewares.resume-stripprefix.stripprefix.prefixes=/api
  resume-client:
    image: amruthpillai/reactive-resume:client-latest
    container_name: resume-client
    environment:
      - TZ=UTC
      - PUBLIC_URL=https://resume.com/
      - PUBLIC_SERVER_URL=https://resume.com/api      
      - PUBLIC_FLAG_DISABLE_SIGNUPS=false
    depends_on:
      - resume-server
    restart: unless-stopped
    networks:
      - lab
    labels:
      - traefik.enable=true
      - traefik.http.routers.resume-client.entrypoints=https
      - traefik.http.routers.resume-client.rule=Host(`resume.com`)
      - traefik.http.routers.resume-client.service=resume-client
      - traefik.http.services.resume-client.loadbalancer.server.port=3000
      - traefik.http.routers.resume-client.tls.certresolver=letsEncrypt      
volumes:
  pgdata:
  
networks:
  lab:
    external: true
```
