### ISSUE TITLE
[BUG] Health of Server Docker Container unhealthy at initialization.

### ISSUE THREAD

**Issue by Death-Pact** [AmruthPillai/Reactive-Resume#958]
**Describe the bug**

When starting Reactive Resume stack on docker, I am met with this error in the server log:

`[Nest] 42  - 08/01/2022, 11:39:16 AM   ERROR [HealthCheckService] Health Check has failed! {"docs":{"status":"down","message":"Request failed with status code 404","statusCode":404,"statusText":"Not Found"}}`

This is the only error I am getting and the container is marked unhealthy. Cannot get it to work. **I can get to the homepage of the app and attempt to login, but cannot successfully login or create an account.**

**Product Flavor**
- [ ] Managed (https://rxresu.me)
- [x] Self Hosted

**To Reproduce**

1. Delete docker volumes
2. update docker images to 'server-latest' & 'client-latest'
3. start stack
4. check logs to see error on the server container.

**Expected behavior**

Server container should start and initialize healthy. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: docker
 - Browser brave

**Additional context**

Here is my docker-compose file (with info redacted.):

---

```
version: '3'

services:
  reactive_resume_postgres:
    image: postgres:14.2-alpine
    container_name: reactive_resume_postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      start_period: 15s
      interval: 30s
      timeout: 30s
      retries: 3
    restart: unless-stopped
    
  reactive_resume_traefik:
    image: traefik:rocamadour
    container_name: reactive_resume_traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:XXXX
    ports:
      - XXXX:XXXX
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  reactive_resume_server:
    image: amruthpillai/reactive-resume:server-latest
    container_name: reactive_resume_server
    environment:
      - TZ=UTC
      - PUBLIC_URL=https://resume.xyz.com
      - PUBLIC_SERVER_URL=https://resume.xyz.com/api
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SECRET_KEY=somelongstring
      - POSTGRES_HOST=reactive_resume_postgres
      - POSTGRES_PORT=5432
      - JWT_SECRET=somelongstring2
      - JWT_EXPIRY_TIME=604800
      - STORAGE_S3_ENABLED=false
    volumes:
      - uploads:/app/server/dist/assets/uploads  
    depends_on:
      - reactive_resume_traefik
      - reactive_resume_postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.server.entrypoints=web
      - traefik.http.routers.server.rule=Host(`resume.xyz.com`) && PathPrefix(`/api/`)
      - traefik.http.routers.server.middlewares=server-stripprefix
      - traefik.http.middlewares.server-stripprefix.stripprefix.prefixes=/api
      - traefik.http.middlewares.server-stripprefix.stripprefix.forceslash=true
    restart: unless-stopped

  reactive_resume_client:
    image: amruthpillai/reactive-resume:client-latest
    container_name: reactive_resume_client
    environment:
      - TZ=UTC
      - PUBLIC_URL=https://resume.xyz.com
      - PUBLIC_SERVER_URL=https://resume.xyz.com/api
      - PUBLIC_FLAG_DISABLE_SIGNUPS=false

    depends_on:
      - reactive_resume_traefik
      - reactive_resume_server
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`resume.xyz.com`)
      - traefik.http.routers.client.entrypoints=web
    restart: unless-stopped

volumes:
  pgdata:
  uploads:
```
