### ISSUE TITLE
[BUG] 404 on login and register pages

### ISSUE THREAD

**Issue by 424778940z** [AmruthPillai/Reactive-Resume#976]
**Describe the bug**
As title suggests, seems not only login, all `/api` url are getting 404, but main page works fine
![404](https://user-images.githubusercontent.com/2379529/185576607-66b8b073-1016-4adb-bf72-9480e0964eae.png)
Also some error in console when `docker-compuse up`
```
server      | [Nest] 41  - 08/19/2022, 8:18:06 AM   ERROR [HealthCheckService] Health Check has failed! {"app":{"status":"up"},"database":{"status":"down","message":"timeout of 1000ms exceeded"},"docs":{"status":"down","message":"Request failed with status code 404","statusCode":404,"statusText":"Not Found"}}
server      | [Nest] 41  - 08/19/2022, 8:18:42 AM   ERROR [HealthCheckService] Health Check has failed! {"database":{"status":"up"},"app":{"status":"up"},"docs":{"status":"down","message":"Request failed with status code 404","statusCode":404,"statusText":"Not Found"}}
server      | [Nest] 41  - 08/19/2022, 8:19:14 AM   ERROR [HealthCheckService] Health Check has failed! {"database":{"status":"up"},"app":{"status":"up"},"docs":{"status":"down","message":"Request failed with status code 404","statusCode":404,"statusText":"Not Found"}}
server      | [Nest] 41  - 08/19/2022, 8:19:47 AM   ERROR [HealthCheckService] Health Check has failed! {"database":{"status":"up"},"app":{"status":"up"},"docs":{"status":"down","message":"Request failed with status code 404","statusCode":404,"statusText":"Not Found"}}
```

**Product Flavor**
- [ ] Managed (https://rxresu.me)
- [x] Self Hosted

**To Reproduce**
Followed this document https://github.com/AmruthPillai/Reactive-Resume/blob/main/docs/docs/deployment/docker.mdx

Here is my `docker-compose.yaml`
```yaml
version: '3'

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      # start_period: 15s # my docker compose do not support this yet
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always

  traefik:
    image: traefik:rocamadour
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  server:
    image: amruthpillai/reactive-resume:server-latest
    # build:
    #   context: .
    #   dockerfile: ./server/Dockerfile
    container_name: server
    environment:
      - TZ=UTC
      - PUBLIC_URL=http://resume.xxxxxxx.com
      - PUBLIC_SERVER_URL=http://resume.xxxxxxx.com/api
      # - PUBLIC_GOOGLE_CLIENT_ID=
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SECRET_KEY=DummyKey
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_SSL_CERT=
      - JWT_SECRET=DummyKey
      - JWT_EXPIRY_TIME=604800
      # - GOOGLE_CLIENT_SECRET=
      # - GOOGLE_API_KEY=
      # - SENDGRID_API_KEY=
      # - SENDGRID_FORGOT_PASSWORD_TEMPLATE_ID=
      # - SENDGRID_FROM_NAME=
      # - SENDGRID_FROM_EMAIL=
      # - STORAGE_BUCKET=
      # - STORAGE_REGION=
      # - STORAGE_ENDPOINT=
      # - STORAGE_URL_PREFIX=
      # - STORAGE_ACCESS_KEY=
      # - STORAGE_SECRET_KEY=
    depends_on:
      - traefik
      - postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.server.entrypoints=web
      - traefik.http.routers.server.rule=Host(`resume.xxxxxxx.com`) && PathPrefix(`/api/`)
      - traefik.http.routers.server.middlewares=server-stripprefix
      - traefik.http.middlewares.server-stripprefix.stripprefix.prefixes=/api
      - traefik.http.middlewares.server-stripprefix.stripprefix.forceslash=true
    restart: always

  client:
    image: amruthpillai/reactive-resume:client-latest
    # build:
    #   context: .
    #   dockerfile: ./client/Dockerfile
    container_name: client
    environment:
      - TZ=UTC
      - PUBLIC_URL=http://resume.xxxxxxx.com
      - PUBLIC_SERVER_URL=http://resume.xxxxxxx.com/api
      # - PUBLIC_GOOGLE_CLIENT_ID=
      - PUBLIC_FLAG_DISABLE_SIGNUPS=false
    depends_on:
      - traefik
      - server
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`resume.xxxxxxx.com`)
      - traefik.http.routers.client.entrypoints=web
    restart: always

volumes:
  pgdata:

```

I also tried with following for client and server but no luck
(I did not put port on traefik.http.routers.client/server.rule) 
```yaml
      - PUBLIC_URL=http://resume.xxxxxxx.com:3000
      - PUBLIC_SERVER_URL=http://resume.xxxxxxx.com:3000/api
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 (access from), Ubuntu 20.04 (Docker host)
 - Browser chrome
 - Version 3.5.3
